"""BEX-5952_db_statuses

Revision ID: 5be3550ee05a
Revises: 06fea10feca6
Create Date: 2024-12-06 20:08:49.751312+00:00

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "5be3550ee05a"
down_revision = "06fea10feca6"
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        """
        ALTER TABLE `annual_insurance_questionnaire_response`
        MODIFY COLUMN `sync_status` enum (
        'ALEGEUS_SUCCESS', 'ALEGEUS_FAILURE', 'ALEGEUS_PRE_EXISTING_ACCOUNT', 'ALEGEUS_MISSING_ACCOUNT', 
        'MISSING_WALLET_ERROR', 'MULTIPLE_WALLETS_ERROR', 'UNKNOWN_ERROR', 'PLAN_ERROR', 'EMPLOYER_PLAN_MISSING_ERROR', 
        'MEMBER_HEALTH_PLAN_OVERLAP_ERROR', 'MEMBER_HEALTH_PLAN_GENERIC_ERROR', 'MEMBER_HEALTH_PLAN_INVALID_DATES_ERROR', 
        'MANUAL_PROCESSING', 'ALEGEUS_SYNCH_INITIATED', 'WAITING_ON_OPS_ACTION', 'MEMBER_HEALTH_PLAN_CREATION_INITIATED', 
        'MEMBER_HEALTH_PLAN_CREATION_SUCCESS', 'MEMBER_HEALTH_PLAN_NOT_NEEDED', 'HDHP_REIMBURSEMENT_PLAN_NOT_NEEDED', 
        'RESPONSE_RECORDED', 'ASYNCH_PROCESSING_INITIATED') COLLATE utf8mb4_unicode_ci DEFAULT NULL, 
        ALGORITHM=COPY ,
        LOCK=SHARED
        """
    )


def downgrade():
    op.execute(
        """
        ALTER TABLE `annual_insurance_questionnaire_response`
        MODIFY COLUMN `sync_status` enum ('ALEGEUS_SUCCESS', 'ALEGEUS_FAILURE', 'ALEGEUS_PRE_EXISTING_ACCOUNT', 'ALEGEUS_MISSING_ACCOUNT', 'MISSING_WALLET_ERROR', 'MULTIPLE_WALLETS_ERROR', 'UNKNOWN_ERROR', 'PLAN_ERROR', 'EMPLOYER_PLAN_MISSING_ERROR', 'MEMBER_HEALTH_PLAN_OVERLAP_ERROR', 'MEMBER_HEALTH_PLAN_GENERIC_ERROR', 'MEMBER_HEALTH_PLAN_INVALID_DATES_ERROR', 'MANUAL_PROCESSING', 'ALEGEUS_SYNCH_INITIATED', 'WAITING_ON_OPS_ACTION', 'MEMBER_HEALTH_PLAN_CREATION_INITIATED', 'MEMBER_HEALTH_PLAN_CREATION_SUCCESS') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        ALGORITHM=COPY ,
        LOCK=SHARED
        """
    )
