apiVersion: apps/v1
kind: Deployment
metadata:
  name: looker
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: looker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: looker
      name: looker
    spec:
      containers:
        - image: gcr.io/maven-clinic-image-builder/looker:latest
          imagePullPolicy: Always
          name: looker
          ports:
            - containerPort: 9999
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 80m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /home/looker/looker
              name: looker-data
      dnsPolicy: ClusterFirst
      nodeSelector:
        maven-node-type: looker
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - gcePersistentDisk:
            fsType: ext4
            pdName: looker-data-plus
          name: looker-data
