apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falco-cluster-role
rules:
  - apiGroups: ["", "extensions"] # "" indicates the core API group
    resources: ["nodes", "namespaces", "pods","replicationcontrollers", "services", "events", "configmaps"]
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/healthz", "/healthz/*"]
    verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: falco-cluster-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: falco-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: falco-cluster-role
  apiGroup: rbac.authorization.k8s.io
