# This object is stored here because of it's size, if you want to use it, use the
# fixture named "search_api_reponse_obj_8_hits" in appointments/conftest.py
search_api_response_8_hits_obj = [
    {
        "_index": "provider_search_index_practitioner_profile",
        "_id": "877915",
        "_score": 4.8638577,
        "_source": {
            "modified_at": "2023-12-02T13:30:59",
            "created_at": "2023-11-27T21:35:31",
            "user_id": 877915,
            "active": 1,
            "role_id": 1,
            "stripe_account_id": None,
            "default_cancellation_policy_id": 3,
            "phone_number": None,
            "reference_quote": None,
            "state_id": None,
            "education": None,
            "work_experience": None,
            "awards": None,
            "dosespot": "{}",
            "booking_buffer": 0,
            "default_prep_buffer": None,
            "next_availability": None,
            "show_when_unavailable": 0,
            "messaging_enabled": 1,
            "response_time": None,
            "anonymous_allowed": 1,
            "ent_national": 0,
            "is_staff": 0,
            "rating": None,
            "zendesk_email": None,
            "show_in_marketplace": 1,
            "show_in_enterprise": 1,
            "json": "{}",
            "experience_started": None,
            "billing_org": None,
            "credential_start": None,
            "note": None,
            "first_name": "Michael",
            "middle_name": None,
            "last_name": "Good",
            "username": None,
            "zendesk_user_id": None,
            "timezone": "UTC",
            "country_code": None,
            "subdivision_code": None,
            "esp_id": "97669f62-f310-4f18-a819-e5b42729adcb",
            "email": None,
            "video_id": None,
        },
    },
    {
        "_index": "provider_search_index_practitioner_profile",
        "_id": "779309",
        "_score": 4.278592,
        "_source": {
            "modified_at": "2023-10-09T17:54:06",
            "created_at": "2023-10-04T22:49:14",
            "user_id": 779309,
            "active": 1,
            "role_id": 1,
            "stripe_account_id": None,
            "default_cancellation_policy_id": 3,
            "phone_number": None,
            "reference_quote": None,
            "state_id": None,
            "education": None,
            "work_experience": None,
            "awards": None,
            "dosespot": "{}",
            "booking_buffer": 0,
            "default_prep_buffer": None,
            "next_availability": None,
            "show_when_unavailable": 0,
            "messaging_enabled": 1,
            "response_time": None,
            "anonymous_allowed": 1,
            "ent_national": 0,
            "is_staff": 0,
            "rating": None,
            "zendesk_email": None,
            "show_in_marketplace": 1,
            "show_in_enterprise": 1,
            "json": "{}",
            "experience_started": None,
            "billing_org": None,
            "credential_start": None,
            "note": None,
            "first_name": "Frank",
            "middle_name": None,
            "last_name": "Ford",
            "username": None,
            "zendesk_user_id": None,
            "timezone": "UTC",
            "country_code": None,
            "subdivision_code": None,
            "esp_id": "352caae7-aee8-4a1a-9f48-cf59879b25d3",
            "email": None,
            "video_id": None,
        },
    },
    {
        "_index": "provider_search_index_need",
        "_id": "45",
        "_score": 3.4922843,
        "_source": {
            "name": "Nutrition",
            "display_order": 0,
            "promote_messaging": 1,
            "description": "Fertility-friendly foods, supplements, managing your weight",
            "created_at": "2023-05-17T21:50:43",
            "id": 45,
            "model_id": ".elser_model_2_linux-x86_64",
            "modified_at": "2023-05-17T21:50:43",
            "hide_from_multitrack": 0,
            "slug": "fert-nutrition",
        },
    },
    {
        "_index": "provider_search_index_need_category",
        "_id": "42",
        "_score": 3.2446494,
        "_source": {
            "created_at": "2024-01-05T16:49:53",
            "description": None,
            "display_order": 57,
            "hide_from_multitrack": 0,
            "id": 42,
            "image_id": "icon-hrt.svg",
            "model_id": ".elser_model_2_linux-x86_64",
            "modified_at": "2024-01-05T16:49:53",
            "slug": "medications",
            "name": "Medications",
            "parent_category_id": None,
        },
    },
    {
        "_index": "provider_search_index_specialty",
        "_id": "47",
        "_score": 2.3771873,
        "_source": {
            "ordering_weight": None,
            "slug": "mood-and-anxiety-disorders",
            "name": "Mood And Anxiety Disorders",
            "id": 47,
            "model_id": ".elser_model_2_linux-x86_64",
            "image_id": None,
        },
    },
    {
        "_index": "provider_search_index_specialty",
        "_id": "53",
        "_score": 2.0960407,
        "_source": {
            "ordering_weight": None,
            "slug": "adolescent-mood-and-anxiety-disorders",
            "name": "Adolescent Mood and Anxiety Disorders",
            "id": 53,
            "model_id": ".elser_model_2_linux-x86_64",
            "image_id": None,
        },
    },
    {
        "_index": "provider_search_index_vertical",
        "_id": "10012",
        "_score": 1.4735041,
        "_source": {
            "promote_messaging": 1,
            "description": "Healthy eating, weight management",
            "pluralized_display_name": "Nutrition Coaches",
            "long_description": "Nutrition Coaches are here to help you understand how diet plays a role in your overall health and well-being, and offer recommendations for foods and small lifestyle changes that can help you feel your best.",
            "model_id": ".elser_model_2_linux-x86_64",
            "display_name": "Nutrition Coach",
            "can_prescribe": 0,
            "deleted_at": None,
            "products": '[{"minutes": 20, "price": 25.0}, {"minutes": 30, "price": 35.0}]',
            "slug": "nutritionist",
            "name": "Nutritionist",
            "promo_end": None,
            "filter_by_state": 0,
            "id": 10012,
            "promo_start": None,
        },
    },
    {
        "_index": "provider_search_index_vertical",
        "_id": "10043",
        "_score": 1.4735041,
        "_source": {
            "promote_messaging": 1,
            "description": "Healthy eating, weight management",
            "pluralized_display_name": "Nutrition Coaches",
            "long_description": "Nutrition Coaches are here to help you understand how diet plays a role in your overall health and well-being, and offer recommendations for foods and small lifestyle changes that can help you feel your best.",
            "model_id": ".elser_model_2_linux-x86_64",
            "display_name": "Nutrition Coach",
            "can_prescribe": 0,
            "deleted_at": "2024-01-05T19:03:46",
            "products": '[{"price": 26.83, "minutes": 20}]',
            "name": "Deleted at 2024-01-05 19:03:46.301212 -- Nutrition Coach",
            "slug": "deleted-at-2024-01-05-19:03:46.301212----nutrition-coach",
            "promo_end": None,
            "filter_by_state": 0,
            "id": 10043,
            "promo_start": None,
        },
    },
]
