# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

install:
  - pip install pytz
  - pip install python-dateutil
  - pip install flake8
  - pip install -U .

before_script:
  - flake8 .

script: python setup.py test
