import os

CONTENTFUL_SPACE_ID = os.getenv("CONTENTFUL_LEARN_SPACE_ID")
CONTENTFUL_MANAGEMENT_KEY = os.getenv("CONTENTFUL_LEARN_MANAGEMENT_KEY")
CONTENTFUL_ENVIRONMENT_ID = os.getenv("CONTENTFUL_LEARN_ENVIRONMENT_ID", "master")
LINE_BREAK_REPLACEMENT_STRING = "REPLACEWITHLINEBREAK"
ACCORDION_REPLACEMENT_STRING = "REPLACEWITHACCORDION"
CALLOUT_REPLACEMENT_STRING = "REPLACEWITHCALLOUT"
IMG_W_CAPTION_REPLACEMENT_STRING = "REPLACEWITHIMGWCAPTION"
IMG_REPLACEMENT_STRING = "REPLACEWITHASSET"
