HEADER_ROW = {
    "processor_routing_identification": {
        "required": True,
        "type": "string",
        "start_pos": 1,
        "end_pos": 200,
        "alignment": "left",
        "padding": " ",
    },
    "record_type": {
        "required": False,
        "type": "string",
        "start_pos": 201,
        "end_pos": 202,
        "alignment": "left",
        "padding": " ",
        "default": "HD",
    },
    "transmission_type": {
        "required": False,
        "type": "string",
        "start_pos": 203,
        "end_pos": 203,
        "alignment": "left",
        "padding": " ",
        "default": "T",
    },
    "creation_date": {
        "required": True,
        "type": "string",
        "start_pos": 204,
        "end_pos": 211,
        "alignment": "left",
        "padding": " ",
    },
    "creation_time": {
        "required": True,
        "type": "string",
        "start_pos": 212,
        "end_pos": 215,
        "alignment": "left",
        "padding": " ",
    },
    "sender_id": {
        "required": False,
        "type": "string",
        "start_pos": 216,
        "end_pos": 245,
        "alignment": "left",
        "padding": " ",
        "default": "MAVN",
    },
    "receiver_id": {
        "required": False,
        "type": "string",
        "start_pos": 246,
        "end_pos": 275,
        "alignment": "left",
        "padding": " ",
        "default": "00825ELEVANCE",
    },
    "batch_number": {
        "required": False,
        "type": "string",
        "start_pos": 276,
        "end_pos": 282,
        "alignment": "right",
        "padding": "0",
        "default": "1",
    },
    "file_type": {
        "required": True,
        "type": "string",
        "start_pos": 283,
        "end_pos": 283,
        "alignment": "left",
        "padding": " ",
    },
    "version_number": {
        "required": False,
        "type": "string",
        "start_pos": 284,
        "end_pos": 285,
        "alignment": "left",
        "padding": " ",
        "default": "01",
    },
    "reserved": {
        "required": False,
        "type": "string",
        "start_pos": 286,
        "end_pos": 1700,
        "alignment": "left",
        "padding": " ",
    },
}

DETAIL_ROW = {
    "processor_routing_identification": {
        "required": False,
        "start_pos": 1,
        "end_pos": 200,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "TBD",
    },
    "record_type": {
        "required": False,
        "start_pos": 201,
        "end_pos": 202,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "DT",
    },
    "transmission_file_type": {
        "required": False,
        "start_pos": 203,
        "end_pos": 204,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "DQ",
    },
    "version_number": {
        "required": False,
        "start_pos": 205,
        "end_pos": 206,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "01",
    },
    "sender_id": {
        "required": False,
        "start_pos": 207,
        "end_pos": 236,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "MAVN",
    },
    "receiver_id": {
        "required": False,
        "start_pos": 237,
        "end_pos": 266,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "00825ELEVANCE",
    },
    "submission_number": {
        "required": False,
        "start_pos": 267,
        "end_pos": 270,
        "padding": "0",
        "alignment": "right",
        "type": "numeric",
    },
    "transaction_response_status": {
        "required": False,
        "start_pos": 271,
        "end_pos": 271,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "reject_code": {
        "required": False,
        "start_pos": 272,
        "end_pos": 274,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "record_length": {
        "required": False,
        "start_pos": 275,
        "end_pos": 279,
        "padding": " ",
        "alignment": "right",
        "type": "numeric",
        "default": "01700",
    },
    "reserved": {
        "required": False,
        "start_pos": 280,
        "end_pos": 299,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "transmission_date": {
        "required": True,
        "start_pos": 300,
        "end_pos": 307,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "transmission_time": {
        "required": True,
        "start_pos": 308,
        "end_pos": 315,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "date_of_service": {
        "required": True,
        "start_pos": 316,
        "end_pos": 323,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "service_provider_id_qualifier": {
        "required": False,
        "start_pos": 324,
        "end_pos": 325,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "service_provider_id": {
        "required": False,
        "start_pos": 326,
        "end_pos": 340,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "document_reference_identifier_qualifier": {
        "required": False,
        "start_pos": 341,
        "end_pos": 342,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "document_reference_identifer": {
        "required": False,
        "start_pos": 343,
        "end_pos": 357,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "transmission_id": {
        "required": True,
        "start_pos": 358,
        "end_pos": 407,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "benefit_type": {
        "required": False,
        "start_pos": 408,
        "end_pos": 408,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "9",
    },
    "in_network_indicator": {
        "required": False,
        "start_pos": 409,
        "end_pos": 409,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "1",
    },
    "formulary_status": {
        "required": False,
        "start_pos": 410,
        "end_pos": 410,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_action_code": {
        "required": False,
        "start_pos": 411,
        "end_pos": 412,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "00",
    },
    "sender_reference_number": {
        "required": False,
        "start_pos": 413,
        "end_pos": 442,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "insurance_code": {
        "required": False,
        "start_pos": 443,
        "end_pos": 462,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "accumulator_balance_benefit_type": {
        "required": False,
        "start_pos": 463,
        "end_pos": 463,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "benefit_effective_date": {
        "required": False,
        "start_pos": 464,
        "end_pos": 471,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "00000000",
    },
    "benefit_termination_date": {
        "required": False,
        "start_pos": 472,
        "end_pos": 479,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "00000000",
    },
    "accumulator_change_source_code": {
        "required": False,
        "start_pos": 480,
        "end_pos": 480,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "transaction_id": {
        "required": True,
        "start_pos": 481,
        "end_pos": 510,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "transaction_id_cross_reference": {
        "required": False,
        "start_pos": 511,
        "end_pos": 540,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "adjustment_reason_code": {
        "required": False,
        "start_pos": 541,
        "end_pos": 541,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "accumulator_reference_time_stamp": {
        "required": False,
        "start_pos": 542,
        "end_pos": 567,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "reserved_2": {
        "required": False,
        "start_pos": 568,
        "end_pos": 580,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "cardholder_id": {
        "required": True,
        "start_pos": 581,
        "end_pos": 600,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "group_id": {
        "required": False,
        "start_pos": 601,
        "end_pos": 615,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "patient_first_name": {
        "required": True,
        "start_pos": 616,
        "end_pos": 640,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "middle_initial": {
        "required": False,
        "start_pos": 641,
        "end_pos": 641,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "patient_last_name": {
        "required": True,
        "start_pos": 642,
        "end_pos": 676,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "patient_relationship_code": {
        "required": True,
        "start_pos": 677,
        "end_pos": 677,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "date_of_birth": {
        "required": True,
        "start_pos": 678,
        "end_pos": 685,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "patient_gender_code": {
        "required": True,
        "start_pos": 686,
        "end_pos": 686,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "patient_state_province_address": {
        "required": False,
        "start_pos": 687,
        "end_pos": 688,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "cardholder_last_name": {
        "required": True,
        "start_pos": 689,
        "end_pos": 723,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "carrier_number": {
        "required": False,
        "start_pos": 724,
        "end_pos": 732,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "contract_number": {
        "required": False,
        "start_pos": 733,
        "end_pos": 747,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "client_pass_through": {
        "required": True,
        "start_pos": 748,
        "end_pos": 797,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "family_id": {
        "required": True,
        "start_pos": 798,
        "end_pos": 817,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "cardholder_id_(alternate)": {
        "required": False,
        "start_pos": 818,
        "end_pos": 837,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "group_id_(alternate)": {
        "required": False,
        "start_pos": 838,
        "end_pos": 852,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "patient_id": {
        "required": False,
        "start_pos": 853,
        "end_pos": 872,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "",
    },
    "person_code": {
        "required": False,
        "start_pos": 873,
        "end_pos": 875,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "reserved_3": {
        "required": False,
        "start_pos": 876,
        "end_pos": 965,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "accumulator_balance_count": {
        "required": False,
        "start_pos": 966,
        "end_pos": 967,
        "padding": " ",
        "alignment": "right",
        "type": "string",
        "default": "02",
    },
    "accumulator_specific_category_type": {
        "required": False,
        "start_pos": 968,
        "end_pos": 969,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "reserved_4": {
        "required": False,
        "start_pos": 970,
        "end_pos": 989,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "accumulator_balance_qualifier_1": {
        "required": True,
        "start_pos": 990,
        "end_pos": 991,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "accumulator_network_indicator_1": {
        "required": False,
        "start_pos": 992,
        "end_pos": 992,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "1",
    },
    "accumulator_applied_amount_1": {
        "required": True,
        "start_pos": 993,
        "end_pos": 1002,
        "padding": "0",
        "alignment": "right",
        "type": "string",
    },
    "action_code_1": {
        "required": False,
        "start_pos": 1003,
        "end_pos": 1003,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_1": {
        "required": False,
        "start_pos": 1004,
        "end_pos": 1013,
        "padding": "0",
        "alignment": "left",
        "type": "string",
    },
    "action_code_1_2": {
        "required": False,
        "start_pos": 1014,
        "end_pos": 1014,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_1": {
        "required": False,
        "start_pos": 1015,
        "end_pos": 1024,
        "padding": "0",
        "alignment": "left",
        "type": "string",
    },
    "action_code_1_3": {
        "required": False,
        "start_pos": 1025,
        "end_pos": 1025,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_qualifier_2": {
        "required": True,
        "start_pos": 1026,
        "end_pos": 1027,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "accumulator_network_indicator_2": {
        "required": False,
        "start_pos": 1028,
        "end_pos": 1028,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "1",
    },
    "accumulator_applied_amount_2": {
        "required": True,
        "start_pos": 1029,
        "end_pos": 1038,
        "padding": "0",
        "alignment": "right",
        "type": "string",
    },
    "action_code_2": {
        "required": False,
        "start_pos": 1039,
        "end_pos": 1039,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_2": {
        "required": False,
        "start_pos": 1040,
        "end_pos": 1049,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_2_2": {
        "required": False,
        "start_pos": 1050,
        "end_pos": 1050,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_2": {
        "required": False,
        "start_pos": 1051,
        "end_pos": 1060,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_2_3": {
        "required": False,
        "start_pos": 1061,
        "end_pos": 1061,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_qualifier_3": {
        "required": False,
        "start_pos": 1062,
        "end_pos": 1063,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_3": {
        "required": False,
        "start_pos": 1064,
        "end_pos": 1064,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_applied_amount_3": {
        "required": False,
        "start_pos": 1065,
        "end_pos": 1074,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_3": {
        "required": False,
        "start_pos": 1075,
        "end_pos": 1075,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_3": {
        "required": False,
        "start_pos": 1076,
        "end_pos": 1085,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_3_2": {
        "required": False,
        "start_pos": 1086,
        "end_pos": 1086,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_3": {
        "required": False,
        "start_pos": 1087,
        "end_pos": 1096,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_3_3": {
        "required": False,
        "start_pos": 1097,
        "end_pos": 1097,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_qualifier_4": {
        "required": False,
        "start_pos": 1098,
        "end_pos": 1099,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_4": {
        "required": False,
        "start_pos": 1100,
        "end_pos": 1100,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_applied_amount_4": {
        "required": False,
        "start_pos": 1101,
        "end_pos": 1110,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_4": {
        "required": False,
        "start_pos": 1111,
        "end_pos": 1111,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_4": {
        "required": False,
        "start_pos": 1112,
        "end_pos": 1121,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_4_2": {
        "required": False,
        "start_pos": 1122,
        "end_pos": 1122,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_4": {
        "required": False,
        "start_pos": 1123,
        "end_pos": 1132,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_4_3": {
        "required": False,
        "start_pos": 1133,
        "end_pos": 1133,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_qualifier_5": {
        "required": False,
        "start_pos": 1134,
        "end_pos": 1135,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_5": {
        "required": False,
        "start_pos": 1136,
        "end_pos": 1136,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_applied_amount_5": {
        "required": False,
        "start_pos": 1137,
        "end_pos": 1146,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_5": {
        "required": False,
        "start_pos": 1147,
        "end_pos": 1147,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_5": {
        "required": False,
        "start_pos": 1148,
        "end_pos": 1157,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_5_2": {
        "required": False,
        "start_pos": 1158,
        "end_pos": 1158,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_5": {
        "required": False,
        "start_pos": 1159,
        "end_pos": 1168,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_5_3": {
        "required": False,
        "start_pos": 1169,
        "end_pos": 1169,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_qualifier_6": {
        "required": False,
        "start_pos": 1170,
        "end_pos": 1171,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_6": {
        "required": False,
        "start_pos": 1172,
        "end_pos": 1172,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_applied_amount_6": {
        "required": False,
        "start_pos": 1173,
        "end_pos": 1182,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_6": {
        "required": False,
        "start_pos": 1183,
        "end_pos": 1183,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_6": {
        "required": False,
        "start_pos": 1184,
        "end_pos": 1193,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_6_2": {
        "required": False,
        "start_pos": 1194,
        "end_pos": 1194,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_6": {
        "required": False,
        "start_pos": 1195,
        "end_pos": 1204,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_6_3": {
        "required": False,
        "start_pos": 1205,
        "end_pos": 1205,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "reserved_5": {
        "required": False,
        "start_pos": 1206,
        "end_pos": 1229,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_balance_qualifier_7": {
        "required": False,
        "start_pos": 1230,
        "end_pos": 1231,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_7": {
        "required": False,
        "start_pos": 1232,
        "end_pos": 1232,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_applied_amount_7": {
        "required": False,
        "start_pos": 1233,
        "end_pos": 1242,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_7": {
        "required": False,
        "start_pos": 1243,
        "end_pos": 1243,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_7": {
        "required": False,
        "start_pos": 1244,
        "end_pos": 1253,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_7_2": {
        "required": False,
        "start_pos": 1254,
        "end_pos": 1254,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_7": {
        "required": False,
        "start_pos": 1255,
        "end_pos": 1264,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_7_3": {
        "required": False,
        "start_pos": 1265,
        "end_pos": 1265,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_qualifier_8": {
        "required": False,
        "start_pos": 1266,
        "end_pos": 1267,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_8": {
        "required": False,
        "start_pos": 1268,
        "end_pos": 1268,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_applied_amount_8": {
        "required": False,
        "start_pos": 1269,
        "end_pos": 1278,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_8": {
        "required": False,
        "start_pos": 1279,
        "end_pos": 1279,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_8": {
        "required": False,
        "start_pos": 1280,
        "end_pos": 1289,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_8_2": {
        "required": False,
        "start_pos": 1290,
        "end_pos": 1290,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_8": {
        "required": False,
        "start_pos": 1291,
        "end_pos": 1300,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_8_3": {
        "required": False,
        "start_pos": 1301,
        "end_pos": 1301,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_qualifier_9": {
        "required": False,
        "start_pos": 1302,
        "end_pos": 1303,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_9": {
        "required": False,
        "start_pos": 1304,
        "end_pos": 1304,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_applied_amount_9": {
        "required": False,
        "start_pos": 1305,
        "end_pos": 1314,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_9": {
        "required": False,
        "start_pos": 1315,
        "end_pos": 1315,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_9": {
        "required": False,
        "start_pos": 1316,
        "end_pos": 1325,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_9_2": {
        "required": False,
        "start_pos": 1326,
        "end_pos": 1326,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_9": {
        "required": False,
        "start_pos": 1327,
        "end_pos": 1336,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_9_3": {
        "required": False,
        "start_pos": 1337,
        "end_pos": 1337,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_qualifier_10": {
        "required": False,
        "start_pos": 1338,
        "end_pos": 1339,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_10": {
        "required": False,
        "start_pos": 1340,
        "end_pos": 1340,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_applied_amount_10": {
        "required": False,
        "start_pos": 1341,
        "end_pos": 1350,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_10": {
        "required": False,
        "start_pos": 1351,
        "end_pos": 1351,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_10": {
        "required": False,
        "start_pos": 1352,
        "end_pos": 1361,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_10_2": {
        "required": False,
        "start_pos": 1362,
        "end_pos": 1362,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_10": {
        "required": False,
        "start_pos": 1363,
        "end_pos": 1372,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_10_3": {
        "required": False,
        "start_pos": 1373,
        "end_pos": 1373,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_qualifier_11": {
        "required": False,
        "start_pos": 1374,
        "end_pos": 1375,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_11": {
        "required": False,
        "start_pos": 1376,
        "end_pos": 1376,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_applied_amount_11": {
        "required": False,
        "start_pos": 1377,
        "end_pos": 1386,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_11": {
        "required": False,
        "start_pos": 1387,
        "end_pos": 1387,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_11": {
        "required": False,
        "start_pos": 1388,
        "end_pos": 1397,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_11_2": {
        "required": False,
        "start_pos": 1398,
        "end_pos": 1398,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_11": {
        "required": False,
        "start_pos": 1399,
        "end_pos": 1408,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_11_3": {
        "required": False,
        "start_pos": 1409,
        "end_pos": 1409,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_qualifier_12": {
        "required": False,
        "start_pos": 1410,
        "end_pos": 1411,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_12": {
        "required": False,
        "start_pos": 1412,
        "end_pos": 1412,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_applied_amount_12": {
        "required": False,
        "start_pos": 1413,
        "end_pos": 1422,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_12": {
        "required": False,
        "start_pos": 1423,
        "end_pos": 1423,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_12": {
        "required": False,
        "start_pos": 1424,
        "end_pos": 1433,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_12_2": {
        "required": False,
        "start_pos": 1434,
        "end_pos": 1434,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_12": {
        "required": False,
        "start_pos": 1435,
        "end_pos": 1444,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_12_3": {
        "required": False,
        "start_pos": 1445,
        "end_pos": 1445,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "optional_data_indicator": {
        "required": False,
        "start_pos": 1446,
        "end_pos": 1446,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "N",
    },
    "total_amount_paid": {
        "required": False,
        "start_pos": 1447,
        "end_pos": 1456,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_1_4": {
        "required": False,
        "start_pos": 1457,
        "end_pos": 1457,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "amount_of_copay": {
        "required": False,
        "start_pos": 1458,
        "end_pos": 1467,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_2_4": {
        "required": False,
        "start_pos": 1468,
        "end_pos": 1468,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "patient_pay_amount": {
        "required": False,
        "start_pos": 1469,
        "end_pos": 1478,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_3_4": {
        "required": False,
        "start_pos": 1479,
        "end_pos": 1479,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "amount_attributed_to_product_selection_brand": {
        "required": False,
        "start_pos": 1480,
        "end_pos": 1489,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_4_4": {
        "required": False,
        "start_pos": 1490,
        "end_pos": 1490,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "amount_attributed_to_sales_tax": {
        "required": False,
        "start_pos": 1491,
        "end_pos": 1500,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_5_4": {
        "required": False,
        "start_pos": 1501,
        "end_pos": 1501,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "amount_attributed_to_processor_fee": {
        "required": False,
        "start_pos": 1502,
        "end_pos": 1511,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_6_4": {
        "required": False,
        "start_pos": 1512,
        "end_pos": 1512,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "gross_amount_due": {
        "required": False,
        "start_pos": 1513,
        "end_pos": 1522,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_7_4": {
        "required": False,
        "start_pos": 1523,
        "end_pos": 1523,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "invoiced_amount": {
        "required": False,
        "start_pos": 1524,
        "end_pos": 1533,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_8_4": {
        "required": False,
        "start_pos": 1534,
        "end_pos": 1534,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "penalty_amount": {
        "required": False,
        "start_pos": 1535,
        "end_pos": 1544,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_9_4": {
        "required": False,
        "start_pos": 1545,
        "end_pos": 1545,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "reserved_6": {
        "required": False,
        "start_pos": 1546,
        "end_pos": 1568,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "product_service_id_qualifier": {
        "required": False,
        "start_pos": 1569,
        "end_pos": 1570,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "product_service_id": {
        "required": False,
        "start_pos": 1571,
        "end_pos": 1589,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "days_supply": {
        "required": False,
        "start_pos": 1590,
        "end_pos": 1592,
        "padding": "0",
        "alignment": "right",
        "type": "numeric",
        "default": "0",
    },
    "quantity_dispense": {
        "required": False,
        "start_pos": 1593,
        "end_pos": 1602,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "product_service_name": {
        "required": False,
        "start_pos": 1603,
        "end_pos": 1632,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "brand_generic_indicator": {
        "required": False,
        "start_pos": 1633,
        "end_pos": 1633,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "therapeutic_class_code_qualifier": {
        "required": False,
        "start_pos": 1634,
        "end_pos": 1634,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "therapeutic_class_code_–_specific": {
        "required": False,
        "start_pos": 1635,
        "end_pos": 1651,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "dispensed_as_written_product_selection": {
        "required": False,
        "start_pos": 1652,
        "end_pos": 1652,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "reserved_7": {
        "required": False,
        "start_pos": 1653,
        "end_pos": 1700,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
}

TRAILER_ROW = {
    "processor_routing_identification": {
        "required": True,
        "type": "string",
        "start_pos": 1,
        "end_pos": 200,
        "alignment": "left",
        "padding": " ",
    },
    "record_type": {
        "required": False,
        "type": "string",
        "start_pos": 201,
        "end_pos": 202,
        "alignment": "left",
        "padding": " ",
        "default": "TR",
    },
    "batch_number": {
        "required": False,
        "type": "string",
        "start_pos": 203,
        "end_pos": 209,
        "alignment": "right",
        "padding": "0",
        "default": "1",
    },
    "record_count": {
        "required": True,
        "type": "numeric",
        "start_pos": 210,
        "end_pos": 219,
        "alignment": "right",
        "padding": "0",
    },
    "message": {
        "required": False,
        "type": "string",
        "start_pos": 220,
        "end_pos": 299,
        "alignment": "left",
        "padding": " ",
    },
    "reserved": {
        "required": False,
        "type": "string",
        "start_pos": 300,
        "end_pos": 1700,
        "alignment": "left",
        "padding": " ",
    },
}
