DETAIL_SEGMENT_LENGTH = 158
ACCUMULATION_SEGMENT_LENGTH = 23

HEADER_ROW = {}

DETAIL_ROW = {
    "member_pid": {
        "required": True,
        "type": "string",
        "start_pos": 1,
        "end_pos": 15,
        "alignment": "left",
        "padding": " ",
    },
    "employee_pid": {
        "required": False,
        "default": "",
        "type": "string",
        "start_pos": 16,
        "end_pos": 30,
        "alignment": "left",
        "padding": " ",
    },
    "employee_id": {
        "required": False,
        "default": "000000000",
        "type": "string",
        "start_pos": 31,
        "end_pos": 39,
        "alignment": "right",
        "padding": "0",
    },
    "member_first_name": {
        "required": True,
        "type": "string",
        "start_pos": 40,
        "end_pos": 54,
        "alignment": "left",
        "padding": " ",
    },
    "member_last_name": {
        "required": True,
        "type": "string",
        "start_pos": 55,
        "end_pos": 89,
        "alignment": "left",
        "padding": " ",
    },
    "member_dob": {
        "required": True,
        "type": "string",
        "start_pos": 90,
        "end_pos": 99,
        "alignment": "left",
        "padding": " ",
    },
    "member_sex": {
        "required": True,
        "type": "string",
        "start_pos": 100,
        "end_pos": 100,
        "alignment": "left",
        "padding": " ",
    },
    "relationship_code": {
        "required": True,
        "type": "string",
        "start_pos": 101,
        "end_pos": 102,
        "alignment": "left",
        "padding": " ",
    },
    "id_card_extension": {
        "required": False,
        "default": "",
        "type": "string",
        "start_pos": 103,
        "end_pos": 104,
        "alignment": "left",
        "padding": "0",
    },
    "date_of_service": {
        "required": True,
        "type": "string",
        "start_pos": 105,
        "end_pos": 112,
        "alignment": "left",
        "padding": " ",
    },
    "client_number": {
        "required": False,
        "default": "",
        "type": "string",
        "start_pos": 113,
        "end_pos": 119,
        "alignment": "right",
        "padding": "0",
    },
    "account": {
        "required": False,
        "default": "",
        "type": "string",
        "start_pos": 120,
        "end_pos": 126,
        "alignment": "right",
        "padding": "0",
    },
    "branch": {
        "required": False,
        "default": "",
        "type": "string",
        "start_pos": 127,
        "end_pos": 132,
        "alignment": "left",
        "padding": " ",
    },
    "benefit_option": {
        "required": False,
        "default": "",
        "type": "string",
        "start_pos": 133,
        "end_pos": 137,
        "alignment": "left",
        "padding": " ",
    },
    "message_date": {
        "required": True,
        "type": "string",
        "start_pos": 138,
        "end_pos": 145,
        "alignment": "left",
        "padding": " ",
    },
    "message_time": {
        "required": True,
        "type": "string",
        "start_pos": 146,
        "end_pos": 153,
        "alignment": "left",
        "padding": "0",
    },
    "source_system": {
        "required": True,
        "type": "string",
        "start_pos": 154,
        "end_pos": 154,
        "alignment": "left",
        "padding": " ",
    },
    "accumulation_counter": {
        "required": True,
        "type": "string",
        "start_pos": 155,
        "end_pos": 158,
        "alignment": "right",
        "padding": "0",
    },
}

# Will need to do some messing about to see if we can reuse this section repeatedly per row to fill in accumulations
ACCUMULATION_SEGMENT = {
    "network_code": {
        "required": False,
        "default": "I",
        "type": "string",
        "start_pos": 1,
        "end_pos": 1,
        "alignment": "left",
        "padding": " ",
    },
    "member_family_code": {
        "required": False,
        "default": "M",
        "type": "string",
        "start_pos": 2,
        "end_pos": 2,
        "alignment": "left",
        "padding": " ",
    },
    "accumulator_type": {
        "required": True,
        "type": "string",
        "start_pos": 3,
        "end_pos": 3,
        "alignment": "left",
        "padding": " ",
    },
    "oop_indicator": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 4,
        "end_pos": 4,
        "alignment": "left",
        "padding": " ",
    },
    "units_indicator": {
        "required": False,
        "default": "D",
        "type": "string",
        "start_pos": 5,
        "end_pos": 5,
        "alignment": "left",
        "padding": " ",
    },
    "amount": {
        "required": True,
        "type": "string",
        "start_pos": 6,
        "end_pos": 14,
        "alignment": "right",
        "padding": "0",
    },
    "accumulation_balance": {
        "required": False,
        "default": "00000000{",
        "type": "string",
        "start_pos": 15,
        "end_pos": 23,
        "alignment": "right",
        "padding": "0",
    },
}


TRAILER_ROW = {}
