HEADER_ROW = {
    "record_type": {
        "required": False,
        "default": "HEADER",
        "type": "string",
        "start_pos": 1,
        "end_pos": 7,
        "alignment": "left",
        "padding": " ",
    },
    "test_production_indicator": {
        "required": False,
        "default": "P",
        "type": "string",
        "start_pos": 8,
        "end_pos": 8,
        "alignment": "left",
        "padding": " ",
    },
    "sender_id": {
        "required": False,
        "default": "MAVEN",
        "type": "string",
        "start_pos": 9,
        "end_pos": 28,
        "alignment": "left",
        "padding": " ",
    },
    "file_date": {
        "required": True,
        "type": "string",
        "start_pos": 29,
        "end_pos": 36,
        "alignment": "left",
        "padding": " ",
    },
    "file_time": {
        "required": True,
        "type": "string",
        "start_pos": 37,
        "end_pos": 42,
        "alignment": "left",
        "padding": " ",
    },
    "receiver_of_transmission": {
        "required": False,
        "default": "CREDENCE",
        "type": "string",
        "start_pos": 43,
        "end_pos": 67,
        "alignment": "left",
        "padding": " ",
    },
    "unique_file_id": {
        "required": True,
        "type": "string",
        "start_pos": 68,
        "end_pos": 107,
        "alignment": "left",
        "padding": " ",
    },
    "filler": {
        "required": False,
        "type": "string",
        "start_pos": 108,
        "end_pos": 1100,
        "alignment": "left",
        "padding": " ",
    },
}

DETAIL_ROW = {
    "record_type": {
        "required": False,
        "default": "01",
        "type": "string",
        "start_pos": 1,
        "end_pos": 2,
        "alignment": "left",
        "padding": " ",
    },
    "transaction_type": {
        "required": False,
        "default": "00",
        "type": "string",
        "start_pos": 3,
        "end_pos": 4,
        "alignment": "left",
        "padding": " ",
    },
    "sender_id": {
        "required": False,
        "default": "MAVEN",
        "type": "string",
        "start_pos": 5,
        "end_pos": 29,
        "alignment": "left",
        "padding": " ",
    },
    "sender_name": {
        "required": False,
        "default": "MAVEN",
        "type": "string",
        "start_pos": 30,
        "end_pos": 89,
        "alignment": "left",
        "padding": " ",
    },
    "receiver_id": {
        "required": False,
        "default": "BCBSAL",
        "type": "string",
        "start_pos": 90,
        "end_pos": 114,
        "alignment": "left",
        "padding": " ",
    },
    "receiver_name": {
        "required": False,
        "default": "BCBSAL",
        "type": "string",
        "start_pos": 115,
        "end_pos": 174,
        "alignment": "left",
        "padding": " ",
    },
    "unique_record_identifier": {
        "required": True,
        "type": "string",
        "start_pos": 175,
        "end_pos": 249,
        "alignment": "left",
        "padding": " ",
    },
    "benefit_type": {
        "required": False,
        "default": "04",
        "type": "string",
        "start_pos": 250,
        "end_pos": 251,
        "alignment": "left",
        "padding": " ",
    },
    "subscriber_ssn": {
        "required": False,
        "type": "string",
        "start_pos": 252,
        "end_pos": 260,
        "alignment": "left",
        "padding": " ",
    },
    "subscriber_last_name": {
        "required": True,
        "type": "string",
        "start_pos": 261,
        "end_pos": 295,
        "alignment": "left",
        "padding": " ",
    },
    "relationship_code": {
        "required": True,
        "type": "string",
        "start_pos": 296,
        "end_pos": 296,
        "alignment": "left",
        "padding": " ",
    },
    "patient_ssn": {
        "required": False,
        "type": "string",
        "start_pos": 297,
        "end_pos": 305,
        "alignment": "left",
        "padding": " ",
    },
    "patient_first_name": {
        "required": True,
        "type": "string",
        "start_pos": 306,
        "end_pos": 330,
        "alignment": "left",
        "padding": " ",
    },
    "patient_last_name": {
        "required": True,
        "type": "string",
        "start_pos": 331,
        "end_pos": 365,
        "alignment": "left",
        "padding": " ",
    },
    "patient_date_of_birth": {
        "required": True,
        "type": "string",
        "start_pos": 366,
        "end_pos": 373,
        "alignment": "left",
        "padding": " ",
    },
    "patient_gender": {
        "required": True,
        "type": "string",
        "start_pos": 374,
        "end_pos": 374,
        "alignment": "left",
        "padding": " ",
    },
    "claim_number": {
        "required": True,
        "type": "string",
        "start_pos": 375,
        "end_pos": 434,
        "alignment": "left",
        "padding": " ",
    },
    "claim_line_number": {
        "required": False,
        "type": "string",
        "start_pos": 435,
        "end_pos": 436,
        "alignment": "left",
        "padding": "0",
    },
    "claim_start_date": {
        "required": True,
        "type": "string",
        "start_pos": 437,
        "end_pos": 444,
        "alignment": "left",
        "padding": " ",
    },
    "claim_end_date": {
        "required": True,
        "type": "string",
        "start_pos": 445,
        "end_pos": 452,
        "alignment": "left",
        "padding": " ",
    },
    "family_or_individual": {
        "required": False,
        "default": "I",
        "type": "string",
        "start_pos": 453,
        "end_pos": 453,
        "alignment": "left",
        "padding": " ",
    },
    "group_number": {
        "required": False,
        "default": "0000000",
        "type": "string",
        "start_pos": 454,
        "end_pos": 460,
        "alignment": "left",
        "padding": " ",
    },
    "procedure_code": {
        "required": False,
        "type": "string",
        "start_pos": 461,
        "end_pos": 470,
        "alignment": "left",
        "padding": " ",
    },
    "primacy_diagnosis_code": {
        "required": False,
        "type": "string",
        "start_pos": 471,
        "end_pos": 480,
        "alignment": "left",
        "padding": " ",
    },
    "place_of_treatment": {
        "required": False,
        "type": "string",
        "start_pos": 481,
        "end_pos": 482,
        "alignment": "left",
        "padding": " ",
    },
    "type_service": {
        "required": False,
        "type": "string",
        "start_pos": 483,
        "end_pos": 484,
        "alignment": "left",
        "padding": " ",
    },
    "number_days_service": {
        "required": False,
        "type": "string",
        "start_pos": 485,
        "end_pos": 487,
        "alignment": "left",
        "padding": " ",
    },
    "paid_amount": {
        "required": False,
        "type": "string",
        "start_pos": 488,
        "end_pos": 499,
        "alignment": "left",
        "padding": " ",
    },
    "filler_1": {
        "required": False,
        "type": "string",
        "start_pos": 500,
        "end_pos": 500,
        "alignment": "left",
        "padding": " ",
    },
    "contract_number": {
        "required": True,
        "type": "string",
        "start_pos": 501,
        "end_pos": 515,
        "alignment": "left",
        "padding": " ",
    },
    "prescription_number": {
        "required": False,
        "type": "string",
        "start_pos": 516,
        "end_pos": 526,
        "alignment": "left",
        "padding": " ",
    },
    "ndc_code": {
        "required": False,
        "type": "string",
        "start_pos": 527,
        "end_pos": 537,
        "alignment": "left",
        "padding": " ",
    },
    "pharmacy_npi": {
        "required": False,
        "type": "string",
        "start_pos": 538,
        "end_pos": 547,
        "alignment": "left",
        "padding": " ",
    },
    "division": {
        "required": False,
        "type": "string",
        "start_pos": 548,
        "end_pos": 550,
        "alignment": "left",
        "padding": " ",
    },
    "filler_2": {
        "required": False,
        "type": "string",
        "start_pos": 551,
        "end_pos": 597,
        "alignment": "left",
        "padding": " ",
    },
    "oop_eob_applied_amount": {
        "required": False,
        "type": "string",
        "start_pos": 598,
        "end_pos": 609,
        "alignment": "right",
        "padding": "0",
    },
    "filler_3": {
        "required": False,
        "type": "string",
        "start_pos": 610,
        "end_pos": 760,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_accumulator_1": {
        "required": True,
        "type": "string",
        "start_pos": 761,
        "end_pos": 761,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_coverage_1": {
        "required": True,
        "type": "string",
        "start_pos": 762,
        "end_pos": 762,
        "alignment": "left",
        "padding": " ",
    },
    "accumulator_amount_1": {
        "required": True,
        "type": "string",
        "start_pos": 763,
        "end_pos": 774,
        "alignment": "right",
        "padding": "0",
    },
    "filler_4": {
        "required": False,
        "type": "string",
        "start_pos": 775,
        "end_pos": 794,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_accumulator_2": {
        "required": False,
        "type": "string",
        "start_pos": 795,
        "end_pos": 795,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_coverage_2": {
        "required": False,
        "type": "string",
        "start_pos": 796,
        "end_pos": 796,
        "alignment": "left",
        "padding": " ",
    },
    "accumulator_amount_2": {
        "required": False,
        "type": "string",
        "start_pos": 797,
        "end_pos": 808,
        "alignment": "right",
        "padding": "0",
    },
    "filler_5": {
        "required": False,
        "type": "string",
        "start_pos": 809,
        "end_pos": 828,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_accumulator_3": {
        "required": False,
        "type": "string",
        "start_pos": 829,
        "end_pos": 829,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_coverage_3": {
        "required": False,
        "type": "string",
        "start_pos": 830,
        "end_pos": 830,
        "alignment": "left",
        "padding": " ",
    },
    "accumulator_amount_3": {
        "required": False,
        "type": "string",
        "start_pos": 831,
        "end_pos": 842,
        "alignment": "right",
        "padding": "0",
    },
    "filler_6": {
        "required": False,
        "type": "string",
        "start_pos": 843,
        "end_pos": 862,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_accumulator_4": {
        "required": False,
        "type": "string",
        "start_pos": 863,
        "end_pos": 863,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_coverage_4": {
        "required": False,
        "type": "string",
        "start_pos": 864,
        "end_pos": 864,
        "alignment": "left",
        "padding": " ",
    },
    "accumulator_amount_4": {
        "required": False,
        "type": "string",
        "start_pos": 865,
        "end_pos": 876,
        "alignment": "right",
        "padding": "0",
    },
    "filler_7": {
        "required": False,
        "type": "string",
        "start_pos": 877,
        "end_pos": 896,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_accumulator_5": {
        "required": False,
        "type": "string",
        "start_pos": 897,
        "end_pos": 897,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_coverage_5": {
        "required": False,
        "type": "string",
        "start_pos": 898,
        "end_pos": 898,
        "alignment": "left",
        "padding": " ",
    },
    "accumulator_amount_5": {
        "required": False,
        "type": "string",
        "start_pos": 899,
        "end_pos": 910,
        "alignment": "right",
        "padding": "0",
    },
    "filler_8": {
        "required": False,
        "type": "string",
        "start_pos": 911,
        "end_pos": 930,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_accumulator_6": {
        "required": False,
        "type": "string",
        "start_pos": 931,
        "end_pos": 931,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_coverage_6": {
        "required": False,
        "type": "string",
        "start_pos": 932,
        "end_pos": 932,
        "alignment": "left",
        "padding": " ",
    },
    "accumulator_amount_6": {
        "required": False,
        "type": "string",
        "start_pos": 933,
        "end_pos": 944,
        "alignment": "right",
        "padding": "0",
    },
    "filler_9": {
        "required": False,
        "type": "string",
        "start_pos": 945,
        "end_pos": 964,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_accumulator_7": {
        "required": False,
        "type": "string",
        "start_pos": 965,
        "end_pos": 965,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_coverage_7": {
        "required": False,
        "type": "string",
        "start_pos": 966,
        "end_pos": 966,
        "alignment": "left",
        "padding": " ",
    },
    "accumulator_amount_7": {
        "required": False,
        "type": "string",
        "start_pos": 967,
        "end_pos": 978,
        "alignment": "right",
        "padding": "0",
    },
    "filler_10": {
        "required": False,
        "type": "string",
        "start_pos": 979,
        "end_pos": 998,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_accumulator_8": {
        "required": False,
        "type": "string",
        "start_pos": 999,
        "end_pos": 999,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_coverage_8": {
        "required": False,
        "type": "string",
        "start_pos": 1000,
        "end_pos": 1000,
        "alignment": "left",
        "padding": " ",
    },
    "accumulator_amount_8": {
        "required": False,
        "type": "string",
        "start_pos": 1001,
        "end_pos": 1012,
        "alignment": "right",
        "padding": "0",
    },
    "filler_11": {
        "required": False,
        "type": "string",
        "start_pos": 1013,
        "end_pos": 1032,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_accumulator_9": {
        "required": False,
        "type": "string",
        "start_pos": 1033,
        "end_pos": 1033,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_coverage_9": {
        "required": False,
        "type": "string",
        "start_pos": 1034,
        "end_pos": 1034,
        "alignment": "left",
        "padding": " ",
    },
    "accumulator_amount_9": {
        "required": False,
        "type": "string",
        "start_pos": 1035,
        "end_pos": 1046,
        "alignment": "right",
        "padding": "0",
    },
    "filler_12": {
        "required": False,
        "type": "string",
        "start_pos": 1047,
        "end_pos": 1066,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_accumulator_10": {
        "required": False,
        "type": "string",
        "start_pos": 1067,
        "end_pos": 1067,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_coverage_10": {
        "required": False,
        "type": "string",
        "start_pos": 1068,
        "end_pos": 1068,
        "alignment": "left",
        "padding": " ",
    },
    "accumulator_amount_10": {
        "required": False,
        "type": "string",
        "start_pos": 1069,
        "end_pos": 1080,
        "alignment": "right",
        "padding": "0",
    },
    "filler_13": {
        "required": False,
        "type": "string",
        "start_pos": 1081,
        "end_pos": 1084,
        "alignment": "left",
        "padding": " ",
    },
    "out_of_pocket_amount": {
        "required": False,
        "type": "string",
        "start_pos": 1085,
        "end_pos": 1096,
        "alignment": "right",
        "padding": "0",
    },
    "acknowledgement_code": {
        "required": False,
        "default": "00",
        "type": "string",
        "start_pos": 1097,
        "end_pos": 1098,
        "alignment": "left",
        "padding": " ",
    },
    "acknowledgement_sub_code": {
        "required": False,
        "default": "",
        "type": "string",
        "start_pos": 1099,
        "end_pos": 1100,
        "alignment": "left",
        "padding": " ",
    },
}

TRAILER_ROW = {
    "record_type": {
        "required": False,
        "default": "TRAILER",
        "type": "string",
        "start_pos": 1,
        "end_pos": 7,
        "alignment": "left",
        "padding": " ",
    },
    "record_count": {
        "required": True,
        "type": "string",
        "start_pos": 8,
        "end_pos": 17,
        "alignment": "right",
        "padding": "0",
    },
    "file_date": {
        "required": True,
        "type": "string",
        "start_pos": 18,
        "end_pos": 25,
        "alignment": "left",
        "padding": " ",
    },
    "file_time": {
        "required": True,
        "type": "string",
        "start_pos": 26,
        "end_pos": 31,
        "alignment": "left",
        "padding": " ",
    },
    "transaction_count": {
        "required": True,
        "type": "string",
        "start_pos": 32,
        "end_pos": 41,
        "alignment": "right",
        "padding": "0",
    },
    "filler": {
        "required": False,
        "default": "",
        "type": "string",
        "start_pos": 42,
        "end_pos": 1100,
        "alignment": "left",
        "padding": " ",
    },
}
