HEADER_ROW = {
    "record_type": {
        "required": False,
        "default": "HDR",
        "type": "string",
        "start_pos": 1,
        "end_pos": 3,
        "alignment": "left",
        "padding": " ",
    },
    "unique_batch_file_identifier": {
        "required": True,
        "type": "string",
        "start_pos": 4,
        "end_pos": 25,
        "alignment": "left",
        "padding": " ",
    },
    "record_response_status_code": {
        "required": False,
        "default": "",
        "type": "string",
        "start_pos": 26,
        "end_pos": 26,
        "alignment": "left",
        "padding": " ",
    },
    "reject_code": {
        "required": False,
        "default": "",
        "type": "string",
        "start_pos": 27,
        "end_pos": 29,
        "alignment": "left",
        "padding": " ",
    },
    "data_file_sender_id": {
        "required": False,
        "default": "MAVEN",
        "type": "string",
        "start_pos": 30,
        "end_pos": 34,
        "alignment": "left",
        "padding": " ",
    },
    "data_file_sender_name": {
        "required": False,
        "default": "MAVEN",
        "type": "string",
        "start_pos": 35,
        "end_pos": 49,
        "alignment": "left",
        "padding": " ",
    },
    "data_file_receiver_id": {
        "required": False,
        "default": "LH",
        "type": "string",
        "start_pos": 50,
        "end_pos": 54,
        "alignment": "left",
        "padding": " ",
    },
    "data_file_receiver_name": {
        "required": False,
        "default": "LUMINAREHEALTH",
        "type": "string",
        "start_pos": 55,
        "end_pos": 69,
        "alignment": "left",
        "padding": " ",
    },
    "production_or_test_data": {
        "required": False,
        "default": "P",
        "type": "string",
        "start_pos": 70,
        "end_pos": 70,
        "alignment": "left",
        "padding": " ",
    },
    "transmission_type": {
        "required": False,
        "default": "DQ",
        "type": "string",
        "start_pos": 71,
        "end_pos": 72,
        "alignment": "left",
        "padding": " ",
    },
    "file_counter": {
        "required": False,
        "default": "000",
        "type": "string",
        "start_pos": 73,
        "end_pos": 75,
        "alignment": "left",
        "padding": " ",
    },
    "file_creation_date": {
        "required": True,
        "type": "string",
        "start_pos": 76,
        "end_pos": 83,
        "alignment": "left",
        "padding": " ",
    },
    "file_creation_time": {
        "required": True,
        "type": "string",
        "start_pos": 84,
        "end_pos": 93,
        "alignment": "left",
        "padding": " ",
    },
    "processing_period_start_date": {
        "required": True,
        "type": "string",
        "start_pos": 94,
        "end_pos": 101,
        "alignment": "left",
        "padding": " ",
    },
    "processing_period_start_time": {
        "required": False,
        "default": "120000",
        "type": "string",
        "start_pos": 102,
        "end_pos": 111,
        "alignment": "left",
        "padding": "0",
    },
    "processing_period_end_date": {
        "required": True,
        "type": "string",
        "start_pos": 112,
        "end_pos": 119,
        "alignment": "left",
        "padding": " ",
    },
    "processing_period_end_time": {
        "required": False,
        "default": "115959",
        "type": "string",
        "start_pos": 120,
        "end_pos": 129,
        "alignment": "left",
        "padding": "0",
    },
    "filler": {
        "required": False,
        "default": "",
        "type": "string",
        "start_pos": 130,
        "end_pos": 420,
        "alignment": "left",
        "padding": " ",
    },
}

DETAIL_ROW = {
    "record_type": {
        "required": False,
        "default": "DTL",
        "type": "string",
        "start_pos": 1,
        "end_pos": 3,
        "alignment": "left",
        "padding": " ",
    },
    "unique_record_identifier": {
        "required": True,
        "type": "string",
        "start_pos": 4,
        "end_pos": 53,
        "alignment": "left",
        "padding": " ",
    },
    "claim_source": {
        "required": False,
        "default": "P",
        "type": "string",
        "start_pos": 54,
        "end_pos": 54,
        "alignment": "left",
        "padding": " ",
    },
    "transmission_type": {
        "required": False,
        "default": "DQ",
        "type": "string",
        "start_pos": 55,
        "end_pos": 56,
        "alignment": "left",
        "padding": " ",
    },
    "record_response_status_code": {
        "required": False,
        "default": "",
        "type": "string",
        "start_pos": 57,
        "end_pos": 57,
        "alignment": "left",
        "padding": " ",
    },
    "production_or_test_data": {
        "required": False,
        "default": "P",
        "type": "string",
        "start_pos": 58,
        "end_pos": 58,
        "alignment": "left",
        "padding": " ",
    },
    "record_counter": {
        "required": False,
        "default": "000",
        "type": "string",
        "start_pos": 59,
        "end_pos": 61,
        "alignment": "left",
        "padding": " ",
    },
    "claim_reject_code": {
        "required": False,
        "default": "",
        "type": "string",
        "start_pos": 62,
        "end_pos": 64,
        "alignment": "left",
        "padding": " ",
    },
    "data_file_sender_id": {
        "required": False,
        "default": "MAVEN",
        "type": "string",
        "start_pos": 65,
        "end_pos": 69,
        "alignment": "left",
        "padding": " ",
    },
    "data_file_sender_name": {
        "required": False,
        "default": "MAVEN",
        "type": "string",
        "start_pos": 70,
        "end_pos": 84,
        "alignment": "left",
        "padding": " ",
    },
    "data_file_receiver_id": {
        "required": False,
        "default": "LH",
        "type": "string",
        "start_pos": 85,
        "end_pos": 89,
        "alignment": "left",
        "padding": " ",
    },
    "data_file_receiver_name": {
        "required": False,
        "default": "LUMINAREHEALTH",
        "type": "string",
        "start_pos": 90,
        "end_pos": 104,
        "alignment": "left",
        "padding": " ",
    },
    "client_id_name": {
        "required": False,
        "default": "OhioHealthy",
        "type": "string",
        "start_pos": 105,
        "end_pos": 134,
        "alignment": "left",
        "padding": " ",
    },
    "patient_id": {
        "required": True,
        "type": "string",
        "start_pos": 135,
        "end_pos": 154,
        "alignment": "left",
        "padding": " ",
    },
    "patient_date_of_birth": {
        "required": True,
        "type": "string",
        "start_pos": 155,
        "end_pos": 162,
        "alignment": "left",
        "padding": " ",
    },
    "patient_first_name": {
        "required": True,
        "type": "string",
        "start_pos": 163,
        "end_pos": 177,
        "alignment": "left",
        "padding": " ",
    },
    "patient_middle_initial": {
        "required": False,
        "default": "",
        "type": "string",
        "start_pos": 178,
        "end_pos": 178,
        "alignment": "left",
        "padding": " ",
    },
    "patient_last_name": {
        "required": True,
        "type": "string",
        "start_pos": 179,
        "end_pos": 198,
        "alignment": "left",
        "padding": " ",
    },
    "patient_gender": {
        "required": False,
        "default": "U",
        "type": "string",
        "start_pos": 199,
        "end_pos": 199,
        "alignment": "left",
        "padding": " ",
    },
    "patient_relationship_code": {
        "required": True,
        "type": "string",
        "start_pos": 200,
        "end_pos": 200,
        "alignment": "left",
        "padding": " ",
    },
    "carrier_number": {
        "required": False,
        "type": "string",
        "start_pos": 201,
        "end_pos": 215,
        "alignment": "left",
        "padding": " ",
    },
    "participant_account_number": {
        "required": False,
        "type": "string",
        "start_pos": 216,
        "end_pos": 230,
        "alignment": "left",
        "default": "",
        "padding": " ",
    },
    "group_number": {
        "required": False,
        "type": "string",
        "start_pos": 231,
        "end_pos": 245,
        "alignment": "left",
        "padding": " ",
    },
    "claim_id": {
        "required": True,
        "type": "string",
        "start_pos": 246,
        "end_pos": 270,
        "alignment": "left",
        "padding": " ",
    },
    "claim_sequence_number": {
        "required": False,
        "default": "",
        "type": "string",
        "start_pos": 271,
        "end_pos": 273,
        "alignment": "left",
        "padding": " ",
    },
    "claim_transaction_type": {
        "required": True,
        "type": "string",
        "start_pos": 274,
        "end_pos": 274,
        "alignment": "left",
        "padding": " ",
    },
    "claim_date_of_service": {
        "required": True,
        "type": "string",
        "start_pos": 275,
        "end_pos": 282,
        "alignment": "left",
        "padding": " ",
    },
    "claim_post_date": {
        "required": True,
        "type": "string",
        "start_pos": 283,
        "end_pos": 290,
        "alignment": "left",
        "padding": " ",
    },
    "claim_post_time": {
        "required": True,
        "type": "string",
        "start_pos": 291,
        "end_pos": 300,
        "alignment": "left",
        "padding": " ",
    },
    "dollars_or_flag_indicator": {
        "required": False,
        "default": "D",
        "type": "string",
        "start_pos": 301,
        "end_pos": 301,
        "alignment": "left",
        "padding": " ",
    },
    "deductible_amount_sign": {
        "required": True,
        "type": "string",
        "start_pos": 302,
        "end_pos": 302,
        "alignment": "left",
        "padding": " ",
    },
    "deductible_amount": {
        "required": True,
        "type": "string",
        "start_pos": 303,
        "end_pos": 312,
        "alignment": "right",
        "padding": "0",
    },
    "total_medical_and_pharmacy_deductible_sign": {
        "required": False,
        "type": "string",
        "start_pos": 313,
        "end_pos": 313,
        "alignment": "left",
        "default": "+",
        "padding": " ",
    },
    "total_medical_and_pharmacy_deductible": {
        "required": False,
        "type": "string",
        "start_pos": 314,
        "end_pos": 323,
        "alignment": "right",
        "default": "0",
        "padding": "0",
    },
    "patient_pay_excluding_deductible_amount_sign": {
        "required": False,
        "type": "string",
        "start_pos": 324,
        "end_pos": 324,
        "alignment": "left",
        "default": "+",
        "padding": " ",
    },
    "patient_pay_excluding_deductible_amount": {
        "required": False,
        "type": "string",
        "start_pos": 325,
        "end_pos": 334,
        "alignment": "right",
        "default": "0",
        "padding": "0",
    },
    "out_of_pocket_amount_sign": {
        "required": True,
        "type": "string",
        "start_pos": 335,
        "end_pos": 335,
        "alignment": "left",
        "padding": " ",
    },
    "out_of_pocket_amount": {
        "required": True,
        "type": "string",
        "start_pos": 336,
        "end_pos": 345,
        "alignment": "right",
        "padding": "0",
    },
    "total_medical_and_pharmacy_member_oop_sign": {
        "required": False,
        "type": "string",
        "start_pos": 346,
        "end_pos": 346,
        "alignment": "left",
        "default": "+",
        "padding": " ",
    },
    "total_medical_and_pharmacy_member_oop": {
        "required": False,
        "type": "string",
        "start_pos": 347,
        "end_pos": 356,
        "alignment": "right",
        "default": "0",
        "padding": "0",
    },
    "sponsor_plan_paid_amount_sign": {
        "required": False,
        "type": "string",
        "start_pos": 357,
        "end_pos": 357,
        "alignment": "left",
        "default": "+",
        "padding": " ",
    },
    "sponsor_plan_paid_amount": {
        "required": False,
        "type": "string",
        "start_pos": 358,
        "end_pos": 367,
        "alignment": "right",
        "default": "0",
        "padding": "0",
    },
    "participant_deductible_flag_met": {
        "required": False,
        "default": "N",
        "type": "string",
        "start_pos": 368,
        "end_pos": 368,
        "alignment": "left",
        "padding": " ",
    },
    "family_deductible_flag_met": {
        "required": False,
        "default": "N",
        "type": "string",
        "start_pos": 369,
        "end_pos": 369,
        "alignment": "left",
        "padding": " ",
    },
    "participant_oop_flag_met": {
        "required": False,
        "default": "N",
        "type": "string",
        "start_pos": 370,
        "end_pos": 370,
        "alignment": "left",
        "padding": " ",
    },
    "family_oop_flag_met": {
        "required": False,
        "default": "N",
        "type": "string",
        "start_pos": 371,
        "end_pos": 371,
        "alignment": "left",
        "padding": " ",
    },
    "plan_benefit_begin_date": {
        "required": False,
        "default": "",
        "type": "string",
        "start_pos": 372,
        "end_pos": 379,
        "alignment": "left",
        "padding": " ",
    },
    "plan_benefit_end_date": {
        "required": False,
        "default": "",
        "type": "string",
        "start_pos": 380,
        "end_pos": 387,
        "alignment": "left",
        "padding": " ",
    },
    "network": {
        "required": False,
        "default": "2",
        "type": "string",
        "start_pos": 388,
        "end_pos": 388,
        "alignment": "left",
        "padding": " ",
    },
    "filler": {
        "required": False,
        "default": "",
        "type": "string",
        "start_pos": 389,
        "end_pos": 420,
        "alignment": "left",
        "padding": " ",
    },
}

TRAILER_ROW = {
    "record_type": {
        "required": False,
        "default": "TRL",
        "type": "string",
        "start_pos": 1,
        "end_pos": 3,
        "alignment": "left",
        "padding": " ",
    },
    "total_oop_amount_sign": {
        "required": True,
        "type": "string",
        "start_pos": 4,
        "end_pos": 4,
        "alignment": "left",
        "padding": " ",
    },
    "total_oop_amount": {
        "required": True,
        "type": "string",
        "start_pos": 5,
        "end_pos": 16,
        "alignment": "right",
        "padding": "0",
    },
    "control_record_count": {
        "required": True,
        "type": "string",
        "start_pos": 17,
        "end_pos": 24,
        "alignment": "right",
        "padding": "0",
    },
    "filler": {
        "required": False,
        "default": "",
        "type": "string",
        "start_pos": 25,
        "end_pos": 420,
        "alignment": "left",
        "padding": " ",
    },
}
