HEADER_ROW = {}

DETAIL_ROW = {
    "processor_routing_identification": {
        "required": False,
        "start_pos": 1,
        "end_pos": 200,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "",
    },
    "record_type": {
        "required": False,
        "start_pos": 201,
        "end_pos": 202,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "HD",
    },
    "transmission_file_type": {
        "required": False,
        "start_pos": 203,
        "end_pos": 204,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "DQ",
    },
    "version_number": {
        "required": False,
        "start_pos": 205,
        "end_pos": 206,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "16",
    },
    "sender_id": {
        "required": False,
        "start_pos": 207,
        "end_pos": 236,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "MAVEN",
    },
    "submission_number": {
        "required": False,
        "start_pos": 237,
        "end_pos": 240,
        "padding": "0",
        "alignment": "right",
        "type": "numeric",
    },
    "transaction_response_status": {
        "required": False,
        "start_pos": 241,
        "end_pos": 241,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "reject_code": {
        "required": False,
        "start_pos": 242,
        "end_pos": 244,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "record_length": {
        "required": False,
        "start_pos": 245,
        "end_pos": 249,
        "padding": "0",
        "alignment": "right",
        "type": "numeric",
        "default": "1506",
    },
    "reserved": {
        "required": False,
        "start_pos": 250,
        "end_pos": 269,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "transmission_date": {
        "required": True,
        "start_pos": 270,
        "end_pos": 279,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "transmission_time": {
        "required": True,
        "start_pos": 280,
        "end_pos": 289,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "date_of_service": {
        "required": True,
        "start_pos": 290,
        "end_pos": 299,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "service_provider_id_qualifier": {
        "required": False,
        "start_pos": 300,
        "end_pos": 301,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "service_provider_id": {
        "required": False,
        "start_pos": 302,
        "end_pos": 316,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "document_reference_identifier_qualifier": {
        "required": False,
        "start_pos": 317,
        "end_pos": 318,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "document_reference_identifier": {
        "required": False,
        "start_pos": 319,
        "end_pos": 333,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "transmission_id": {
        "required": True,
        "start_pos": 334,
        "end_pos": 383,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "in_network_indicator": {
        "required": False,
        "start_pos": 384,
        "end_pos": 384,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "1",
    },
    "formulary_status": {
        "required": False,
        "start_pos": 385,
        "end_pos": 385,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_action_code": {
        "required": False,
        "start_pos": 386,
        "end_pos": 387,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "00",
    },
    "sender_reference_number": {
        "required": False,
        "start_pos": 388,
        "end_pos": 417,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "insurance_code": {
        "required": False,
        "start_pos": 418,
        "end_pos": 437,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "accumulator_balance_benefit_type": {
        "required": False,
        "start_pos": 438,
        "end_pos": 438,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "benefit_effective_date": {
        "required": False,
        "start_pos": 439,
        "end_pos": 446,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "00000000",
    },
    "benefit_termination_date": {
        "required": False,
        "start_pos": 447,
        "end_pos": 454,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "00000000",
    },
    "accumulator_change_source_code": {
        "required": False,
        "start_pos": 455,
        "end_pos": 455,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "transaction_id": {
        "required": True,
        "start_pos": 456,
        "end_pos": 485,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "transaction_id_cross_reference": {
        "required": False,
        "start_pos": 486,
        "end_pos": 515,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "adjustment_reason_code": {
        "required": False,
        "start_pos": 516,
        "end_pos": 516,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "S",
    },
    "accumulator_reference_time_stamp": {
        "required": False,
        "start_pos": 517,
        "end_pos": 542,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "reserved_2": {
        "required": False,
        "start_pos": 543,
        "end_pos": 555,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "cardholder_id": {
        "required": True,
        "start_pos": 556,
        "end_pos": 575,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "group_id": {
        "required": True,
        "start_pos": 576,
        "end_pos": 590,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "patient_first_name": {
        "required": True,
        "start_pos": 591,
        "end_pos": 615,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "middle_initial": {
        "required": False,
        "start_pos": 616,
        "end_pos": 616,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "patient_last_name": {
        "required": True,
        "start_pos": 617,
        "end_pos": 651,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "patient_relationship_code": {
        "required": True,
        "start_pos": 652,
        "end_pos": 652,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "date_of_birth": {
        "required": True,
        "start_pos": 653,
        "end_pos": 662,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "patient_gender_code": {
        "required": True,
        "start_pos": 663,
        "end_pos": 663,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "patient_state_province_address": {
        "required": False,
        "start_pos": 664,
        "end_pos": 665,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "cardholder_last_name": {
        "required": False,
        "start_pos": 666,
        "end_pos": 700,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "carrier_number": {
        "required": False,
        "start_pos": 701,
        "end_pos": 709,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "contract_number": {
        "required": False,
        "start_pos": 710,
        "end_pos": 724,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "client_pass_through": {
        "required": False,
        "start_pos": 725,
        "end_pos": 774,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "family_id": {
        "required": False,
        "start_pos": 775,
        "end_pos": 794,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "cardholder_id_alternate": {
        "required": False,
        "start_pos": 795,
        "end_pos": 814,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "group_id_alternate": {
        "required": False,
        "start_pos": 815,
        "end_pos": 829,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "patient_id": {
        "required": True,
        "start_pos": 830,
        "end_pos": 849,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "person_code": {
        "required": False,
        "start_pos": 850,
        "end_pos": 852,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "reserved_3": {
        "required": False,
        "start_pos": 853,
        "end_pos": 942,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "accumulator_balance_count": {
        "required": True,
        "start_pos": 943,
        "end_pos": 944,
        "padding": " ",
        "alignment": "right",
        "type": "string",
    },
    "accumulator_specific_category_type": {
        "required": False,
        "start_pos": 945,
        "end_pos": 946,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "08",
    },
    "reserved_4": {
        "required": False,
        "start_pos": 947,
        "end_pos": 966,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "accumulator_balance_type_1": {
        "required": True,
        "start_pos": 967,
        "end_pos": 968,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "accumulator_network_indicator_1": {
        "required": False,
        "start_pos": 969,
        "end_pos": 969,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "1",
    },
    "accumulator_applied_amount_1": {
        "required": True,
        "start_pos": 970,
        "end_pos": 982,
        "padding": "0",
        "alignment": "right",
        "type": "string",
    },
    "action_code_1": {
        "required": False,
        "start_pos": 983,
        "end_pos": 983,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_1": {
        "required": False,
        "start_pos": 984,
        "end_pos": 996,
        "padding": "0",
        "alignment": "left",
        "type": "string",
    },
    "action_code_1_2": {
        "required": False,
        "start_pos": 997,
        "end_pos": 997,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_1": {
        "required": False,
        "start_pos": 998,
        "end_pos": 1010,
        "padding": "0",
        "alignment": "left",
        "type": "string",
    },
    "action_code_1_3": {
        "required": False,
        "start_pos": 1011,
        "end_pos": 1011,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_type_2": {
        "required": True,
        "start_pos": 1012,
        "end_pos": 1013,
        "padding": " ",
        "alignment": "left",
        "type": "string",
    },
    "accumulator_network_indicator_2": {
        "required": False,
        "start_pos": 1014,
        "end_pos": 1014,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "1",
    },
    "accumulator_applied_amount_2": {
        "required": True,
        "start_pos": 1015,
        "end_pos": 1027,
        "padding": "0",
        "alignment": "right",
        "type": "string",
    },
    "action_code_2": {
        "required": False,
        "start_pos": 1028,
        "end_pos": 1028,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_2": {
        "required": False,
        "start_pos": 1029,
        "end_pos": 1041,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_2_2": {
        "required": False,
        "start_pos": 1042,
        "end_pos": 1042,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_2": {
        "required": False,
        "start_pos": 1043,
        "end_pos": 1055,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_2_3": {
        "required": False,
        "start_pos": 1056,
        "end_pos": 1056,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_type_3": {
        "required": False,
        "start_pos": 1057,
        "end_pos": 1058,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_3": {
        "required": False,
        "start_pos": 1059,
        "end_pos": 1059,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "1",
    },
    "accumulator_applied_amount_3": {
        "required": False,
        "start_pos": 1060,
        "end_pos": 1072,
        "padding": "0",
        "alignment": "right",
        "type": "string",
        "default": "0",
    },
    "action_code_3": {
        "required": False,
        "start_pos": 1073,
        "end_pos": 1073,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_3": {
        "required": False,
        "start_pos": 1074,
        "end_pos": 1086,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_3_2": {
        "required": False,
        "start_pos": 1087,
        "end_pos": 1087,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_3": {
        "required": False,
        "start_pos": 1088,
        "end_pos": 1100,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_3_3": {
        "required": False,
        "start_pos": 1101,
        "end_pos": 1101,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_type_4": {
        "required": False,
        "start_pos": 1102,
        "end_pos": 1103,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_4": {
        "required": False,
        "start_pos": 1104,
        "end_pos": 1104,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_applied_amount_4": {
        "required": False,
        "start_pos": 1105,
        "end_pos": 1117,
        "padding": "0",
        "alignment": "right",
        "type": "string",
        "default": "0",
    },
    "action_code_4": {
        "required": False,
        "start_pos": 1118,
        "end_pos": 1118,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_4": {
        "required": False,
        "start_pos": 1119,
        "end_pos": 1131,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_4_2": {
        "required": False,
        "start_pos": 1132,
        "end_pos": 1132,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_4": {
        "required": False,
        "start_pos": 1133,
        "end_pos": 1145,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_4_3": {
        "required": False,
        "start_pos": 1146,
        "end_pos": 1146,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_type_5": {
        "required": False,
        "start_pos": 1147,
        "end_pos": 1148,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_5": {
        "required": False,
        "start_pos": 1149,
        "end_pos": 1149,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_applied_amount_5": {
        "required": False,
        "start_pos": 1150,
        "end_pos": 1162,
        "padding": "0",
        "alignment": "right",
        "type": "string",
        "default": "0",
    },
    "action_code_5": {
        "required": False,
        "start_pos": 1163,
        "end_pos": 1163,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_5": {
        "required": False,
        "start_pos": 1164,
        "end_pos": 1176,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_5_2": {
        "required": False,
        "start_pos": 1177,
        "end_pos": 1177,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_5": {
        "required": False,
        "start_pos": 1178,
        "end_pos": 1190,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_5_3": {
        "required": False,
        "start_pos": 1191,
        "end_pos": 1191,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_type_6": {
        "required": False,
        "start_pos": 1192,
        "end_pos": 1193,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_6": {
        "required": False,
        "start_pos": 1194,
        "end_pos": 1194,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_applied_amount_6": {
        "required": False,
        "start_pos": 1195,
        "end_pos": 1207,
        "padding": "0",
        "alignment": "right",
        "type": "string",
        "default": "0",
    },
    "action_code_6": {
        "required": False,
        "start_pos": 1208,
        "end_pos": 1208,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_6": {
        "required": False,
        "start_pos": 1209,
        "end_pos": 1221,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_6_2": {
        "required": False,
        "start_pos": 1222,
        "end_pos": 1222,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_6": {
        "required": False,
        "start_pos": 1223,
        "end_pos": 1235,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_6_3": {
        "required": False,
        "start_pos": 1236,
        "end_pos": 1236,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_type_7": {
        "required": False,
        "start_pos": 1237,
        "end_pos": 1238,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_7": {
        "required": False,
        "start_pos": 1239,
        "end_pos": 1239,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_applied_amount_7": {
        "required": False,
        "start_pos": 1240,
        "end_pos": 1252,
        "padding": "0",
        "alignment": "right",
        "type": "string",
        "default": "0",
    },
    "action_code_7": {
        "required": False,
        "start_pos": 1253,
        "end_pos": 1253,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_7": {
        "required": False,
        "start_pos": 1254,
        "end_pos": 1266,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_7_2": {
        "required": False,
        "start_pos": 1267,
        "end_pos": 1267,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_7": {
        "required": False,
        "start_pos": 1268,
        "end_pos": 1280,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_7_3": {
        "required": False,
        "start_pos": 1281,
        "end_pos": 1281,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_type_8": {
        "required": False,
        "start_pos": 1282,
        "end_pos": 1283,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_8": {
        "required": False,
        "start_pos": 1284,
        "end_pos": 1284,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_applied_amount_8": {
        "required": False,
        "start_pos": 1285,
        "end_pos": 1297,
        "padding": "0",
        "alignment": "right",
        "type": "string",
        "default": "0",
    },
    "action_code_8": {
        "required": False,
        "start_pos": 1298,
        "end_pos": 1298,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_8": {
        "required": False,
        "start_pos": 1299,
        "end_pos": 1311,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_8_2": {
        "required": False,
        "start_pos": 1312,
        "end_pos": 1312,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_8": {
        "required": False,
        "start_pos": 1313,
        "end_pos": 1325,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_8_3": {
        "required": False,
        "start_pos": 1326,
        "end_pos": 1326,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_type_9": {
        "required": False,
        "start_pos": 1327,
        "end_pos": 1328,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_9": {
        "required": False,
        "start_pos": 1329,
        "end_pos": 1329,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_applied_amount_9": {
        "required": False,
        "start_pos": 1330,
        "end_pos": 1342,
        "padding": "0",
        "alignment": "right",
        "type": "string",
        "default": "0",
    },
    "action_code_9": {
        "required": False,
        "start_pos": 1343,
        "end_pos": 1343,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_9": {
        "required": False,
        "start_pos": 1344,
        "end_pos": 1356,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_9_2": {
        "required": False,
        "start_pos": 1357,
        "end_pos": 1357,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_9": {
        "required": False,
        "start_pos": 1358,
        "end_pos": 1370,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_9_3": {
        "required": False,
        "start_pos": 1371,
        "end_pos": 1371,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_type_10": {
        "required": False,
        "start_pos": 1372,
        "end_pos": 1373,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_10": {
        "required": False,
        "start_pos": 1374,
        "end_pos": 1374,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_applied_amount_10": {
        "required": False,
        "start_pos": 1375,
        "end_pos": 1387,
        "padding": "0",
        "alignment": "right",
        "type": "string",
        "default": "0",
    },
    "action_code_10": {
        "required": False,
        "start_pos": 1388,
        "end_pos": 1388,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_10": {
        "required": False,
        "start_pos": 1389,
        "end_pos": 1401,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_10_2": {
        "required": False,
        "start_pos": 1402,
        "end_pos": 1402,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_10": {
        "required": False,
        "start_pos": 1403,
        "end_pos": 1415,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_10_3": {
        "required": False,
        "start_pos": 1416,
        "end_pos": 1416,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_type_11": {
        "required": False,
        "start_pos": 1417,
        "end_pos": 1418,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_11": {
        "required": False,
        "start_pos": 1419,
        "end_pos": 1419,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_applied_amount_11": {
        "required": False,
        "start_pos": 1420,
        "end_pos": 1432,
        "padding": "0",
        "alignment": "right",
        "type": "string",
        "default": "0",
    },
    "action_code_11": {
        "required": False,
        "start_pos": 1433,
        "end_pos": 1433,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_11": {
        "required": False,
        "start_pos": 1434,
        "end_pos": 1446,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_11_2": {
        "required": False,
        "start_pos": 1447,
        "end_pos": 1447,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_11": {
        "required": False,
        "start_pos": 1448,
        "end_pos": 1460,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_11_3": {
        "required": False,
        "start_pos": 1461,
        "end_pos": 1461,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_balance_type_12": {
        "required": False,
        "start_pos": 1462,
        "end_pos": 1463,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_network_indicator_12": {
        "required": False,
        "start_pos": 1464,
        "end_pos": 1464,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": " ",
    },
    "accumulator_applied_amount_12": {
        "required": False,
        "start_pos": 1465,
        "end_pos": 1477,
        "padding": "0",
        "alignment": "right",
        "type": "string",
        "default": "0",
    },
    "action_code_12": {
        "required": False,
        "start_pos": 1478,
        "end_pos": 1478,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_benefit_period_amount_12": {
        "required": False,
        "start_pos": 1479,
        "end_pos": 1491,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_12_2": {
        "required": False,
        "start_pos": 1492,
        "end_pos": 1492,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
    "accumulator_remaining_balance_12": {
        "required": False,
        "start_pos": 1493,
        "end_pos": 1505,
        "padding": "0",
        "alignment": "left",
        "type": "string",
        "default": "0",
    },
    "action_code_12_3": {
        "required": False,
        "start_pos": 1506,
        "end_pos": 1506,
        "padding": " ",
        "alignment": "left",
        "type": "string",
        "default": "+",
    },
}

TRAILER_ROW = {
    "processor_routing_identification": {
        "required": False,
        "type": "string",
        "start_pos": 1,
        "end_pos": 200,
        "alignment": "left",
        "padding": " ",
        "default": "",
    },
    "record_type": {
        "required": False,
        "type": "string",
        "start_pos": 201,
        "end_pos": 202,
        "alignment": "left",
        "padding": " ",
        "default": "HT",
    },
    "batch_number": {
        "required": False,
        "type": "string",
        "start_pos": 203,
        "end_pos": 209,
        "alignment": "right",
        "padding": "0",
        "default": "1",
    },
    "record_count": {
        "required": True,
        "type": "numeric",
        "start_pos": 210,
        "end_pos": 219,
        "alignment": "right",
        "padding": "0",
    },
    "message": {
        "required": False,
        "type": "string",
        "start_pos": 220,
        "end_pos": 299,
        "alignment": "left",
        "padding": " ",
    },
}
