HEADER_ROW = {
    "record_code": {
        "required": False,
        "default": "0",
        "type": "string",
        "start_pos": 1,
        "end_pos": 1,
        "alignment": "left",
        "padding": " ",
    },
    "sender_id": {
        "required": False,
        "default": "MAVEN",
        "type": "string",
        "start_pos": 2,
        "end_pos": 11,
        "alignment": "left",
        "padding": " ",
    },
    "processor_name": {
        "required": False,
        "default": "Maven",
        "type": "string",
        "start_pos": 12,
        "end_pos": 31,
        "alignment": "left",
        "padding": " ",
    },
    "processor_address": {
        "required": False,
        "default": "160 Varick St 6th Fl",
        "type": "string",
        "start_pos": 32,
        "end_pos": 51,
        "alignment": "left",
        "padding": " ",
    },
    "processor_city": {
        "required": False,
        "default": "New York",
        "type": "string",
        "start_pos": 52,
        "end_pos": 69,
        "alignment": "left",
        "padding": " ",
    },
    "processor_state": {
        "required": False,
        "default": "NY",
        "type": "string",
        "start_pos": 70,
        "end_pos": 71,
        "alignment": "left",
        "padding": " ",
    },
    "processor_zip": {
        "required": False,
        "default": "10013",
        "type": "string",
        "start_pos": 72,
        "end_pos": 80,
        "alignment": "left",
        "padding": " ",
    },
    "processor_phone": {
        "required": False,
        "default": "2124571790",
        "type": "string",
        "start_pos": 81,
        "end_pos": 90,
        "alignment": "left",
        "padding": " ",
    },
    "receiver_id": {
        "required": False,
        "default": "UHG",
        "type": "string",
        "start_pos": 91,
        "end_pos": 100,
        "alignment": "left",
        "padding": " ",
    },
    "run_date": {
        "required": True,
        "type": "string",
        "start_pos": 101,
        "end_pos": 108,
        "alignment": "left",
        "format": "%Y%m%d",
        "padding": " ",
    },
    "run_time": {
        "required": True,
        "type": "string",
        "start_pos": 109,
        "end_pos": 116,
        "alignment": "left",
        "padding": " ",
    },
    "file_content_type": {
        "required": True,
        "type": "string",
        "start_pos": 117,
        "end_pos": 117,
        "alignment": "left",
        "padding": " ",
    },
    "version_number": {
        "required": False,
        "default": "001",
        "type": "string",
        "start_pos": 118,
        "end_pos": 120,
        "alignment": "left",
        "padding": " ",
    },
    "filler": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 121,
        "end_pos": 600,
        "alignment": "left",
        "padding": " ",
    },
}

DETAIL_ROW = {
    "record_code": {
        "required": False,
        "default": "4",
        "type": "string",
        "start_pos": 1,
        "end_pos": 1,
        "alignment": "left",
        "padding": " ",
    },
    "batch_number": {
        "required": True,
        "type": "string",  # actually a date but fixed width lib doesnt recognize julian date format
        "start_pos": 2,
        "end_pos": 6,
        "alignment": "left",
        "padding": " ",
    },
    "transaction_id": {
        "required": True,
        "type": "string",
        "start_pos": 7,
        "end_pos": 26,
        "alignment": "left",
        "padding": " ",
    },
    "record_type_code": {
        "required": True,
        "type": "string",
        "start_pos": 27,
        "end_pos": 27,
        "alignment": "left",
        "padding": " ",
    },
    "carrier_number": {
        "required": True,
        "type": "string",
        "start_pos": 28,
        "end_pos": 35,
        "alignment": "left",
        "padding": " ",
    },
    "adjustment_type": {
        "required": False,
        "default": "1",
        "type": "string",
        "start_pos": 36,
        "end_pos": 36,
        "alignment": "left",
        "padding": " ",
    },
    "adjustment_code": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 37,
        "end_pos": 38,
        "alignment": "left",
        "padding": " ",
    },
    "adjustment_reason_code": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 39,
        "end_pos": 41,
        "alignment": "left",
        "padding": " ",
    },
    "group_id": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 42,
        "end_pos": 57,
        "alignment": "left",
        "padding": " ",
    },
    "service_reference_number": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 58,
        "end_pos": 66,
        "alignment": "left",
        "padding": " ",
    },
    "fill_number": {
        "required": False,
        "default": "00",
        "type": "string",
        "start_pos": 67,
        "end_pos": 68,
        "alignment": "left",
        "padding": " ",
    },
    "adjudication_date": {  # claim process date
        "required": True,
        "type": "string",
        "start_pos": 69,
        "end_pos": 76,
        "alignment": "left",
        "format": "%Y%m%d",
        "padding": " ",
    },
    "first_date_of_service": {  # claim process date
        "required": True,
        "type": "string",
        "start_pos": 77,
        "end_pos": 84,
        "alignment": "left",
        "format": "%Y%m%d",
        "padding": " ",
    },
    "last_date_of_service": {  # claim process date
        "required": True,
        "type": "string",
        "start_pos": 85,
        "end_pos": 92,
        "alignment": "left",
        "format": "%Y%m%d",
        "padding": " ",
    },
    "cardholder_id": {
        "required": True,
        "type": "string",
        "start_pos": 93,
        "end_pos": 112,
        "alignment": "left",
        "padding": " ",
    },
    "cardholder_id_qualifier": {
        "required": False,
        "default": "99",
        "type": "string",
        "start_pos": 113,
        "end_pos": 114,
        "alignment": "left",
        "padding": " ",
    },
    "patient_id": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 115,
        "end_pos": 134,
        "alignment": "left",
        "padding": " ",
    },
    "patient_first_name": {
        "required": True,
        "type": "string",
        "start_pos": 135,
        "end_pos": 159,
        "alignment": "left",
        "padding": " ",
    },
    "patient_middle_name": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 160,
        "end_pos": 184,
        "alignment": "left",
        "padding": " ",
    },
    "patient_last_name": {
        "required": True,
        "type": "string",
        "start_pos": 185,
        "end_pos": 219,
        "alignment": "left",
        "padding": " ",
    },
    "patient_gender": {
        "required": False,
        "default": "0",
        "type": "string",
        "start_pos": 220,
        "end_pos": 220,
        "alignment": "left",
        "padding": " ",
    },
    "patient_dob": {
        "required": True,
        "type": "string",
        #     "type": "date",
        "start_pos": 221,
        "end_pos": 228,
        "alignment": "left",
        #   "format": "%Y%m%d",
        "padding": " ",
    },
    "patient_relationship_code": {
        "required": True,
        "type": "string",
        "start_pos": 229,
        "end_pos": 229,
        "alignment": "left",
        "padding": " ",
    },
    "service_provider_id_qualifier": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 230,
        "end_pos": 231,
        "alignment": "left",
        "padding": " ",
    },
    "service_provider_id": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 232,
        "end_pos": 241,
        "alignment": "left",
        "padding": " ",
    },
    "pharmacy_chain": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 242,
        "end_pos": 245,
        "alignment": "left",
        "padding": " ",
    },
    "provider_name": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 246,
        "end_pos": 280,
        "alignment": "left",
        "padding": " ",
    },
    "provider_address": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 281,
        "end_pos": 335,
        "alignment": "left",
        "padding": " ",
    },
    "provider_city": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 336,
        "end_pos": 365,
        "alignment": "left",
        "padding": " ",
    },
    "provider_state": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 366,
        "end_pos": 367,
        "alignment": "left",
        "padding": " ",
    },
    "provider_zip": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 368,
        "end_pos": 382,
        "alignment": "left",
        "padding": " ",
    },
    "provider_phone_number": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 383,
        "end_pos": 392,
        "alignment": "left",
        "padding": " ",
    },
    "provider_tax_id_number": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 393,
        "end_pos": 401,
        "alignment": "left",
        "padding": " ",
    },
    "pharmacy_county_code": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 402,
        "end_pos": 404,
        "alignment": "left",
        "padding": " ",
    },
    "pharmacy_class_code": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 405,
        "end_pos": 405,
        "alignment": "left",
        "padding": " ",
    },
    "in_or_out_network_indicator": {
        "required": False,
        "default": "I",
        "type": "string",
        "start_pos": 406,
        "end_pos": 406,
        "alignment": "left",
        "padding": " ",
    },
    "client_amount_due": {
        "required": False,
        "default": "0000000{",
        "type": "string",
        "start_pos": 407,
        "end_pos": 414,
        "alignment": "right",
        "padding": "0",
    },
    "other_payer_amount_paid": {
        "required": False,
        "default": "0000000{",
        "type": "string",
        "start_pos": 415,
        "end_pos": 422,
        "alignment": "right",
        "padding": "0",
    },
    "copay_coinsurance": {
        "required": False,
        "default": "0000000{",
        "type": "string",
        "start_pos": 423,
        "end_pos": 430,
        "alignment": "right",
        "padding": "0",
    },
    "deductible_apply_amount": {
        "required": True,
        "type": "string",
        "start_pos": 431,
        "end_pos": 438,
        "alignment": "right",
        "padding": "0",
    },
    "deductible_total_accumulated_amount": {
        "required": False,
        "default": "000000000{",
        "type": "string",
        "start_pos": 439,
        "end_pos": 448,
        "alignment": "right",
        "padding": "0",
    },
    "deductible_remaining_amount": {
        "required": False,
        "default": "000000000{",
        "type": "string",
        "start_pos": 449,
        "end_pos": 458,
        "alignment": "right",
        "padding": "0",
    },
    "oop_apply_amount": {
        "required": True,
        "type": "string",
        "start_pos": 459,
        "end_pos": 466,
        "alignment": "right",
        "padding": "0",
    },
    "oop_total_accumulated_amount": {
        "required": False,
        "default": "000000000{",
        "type": "string",
        "start_pos": 467,
        "end_pos": 476,
        "alignment": "right",
        "padding": "0",
    },
    "oop_remaining_amount": {
        "required": False,
        "default": "000000000{",
        "type": "string",
        "start_pos": 477,
        "end_pos": 486,
        "alignment": "right",
        "padding": "0",
    },
    "plan_year": {
        "required": True,
        "type": "string",
        "start_pos": 487,
        "end_pos": 494,
        "alignment": "left",
        "padding": " ",
    },
    "subscriber_last_name": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 495,
        "end_pos": 529,
        "alignment": "left",
        "padding": " ",
    },
    "type_of_benefit_ind": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 530,
        "end_pos": 530,
        "alignment": "left",
        "padding": " ",
    },
    "filler": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 531,
        "end_pos": 600,
        "alignment": "left",
        "padding": " ",
    },
}

TRAILER_ROW = {
    "record_code": {
        "required": False,
        "default": "8",
        "type": "string",
        "start_pos": 1,
        "end_pos": 1,
        "alignment": "left",
        "padding": " ",
    },
    "sender_id": {
        "required": False,
        "default": "MAVEN",
        "type": "string",
        "start_pos": 2,
        "end_pos": 11,
        "alignment": "left",
        "padding": " ",
    },
    "transaction_count": {
        "required": True,
        "type": "string",
        "start_pos": 12,
        "end_pos": 21,
        "alignment": "right",
        "padding": "0",
    },
    "total_record_count": {
        "required": True,
        "type": "string",
        "start_pos": 22,
        "end_pos": 31,
        "alignment": "right",
        "padding": "0",
    },
    "filler": {
        "required": False,
        "default": " ",
        "type": "string",
        "start_pos": 32,
        "end_pos": 600,
        "alignment": "left",
        "padding": " ",
    },
}
