import re
import unittest

from ddtrace import tracer

from data_admin.views import FixtureSpecs
from utils.service_owner_mapper import (
    SERVICE_NS_TAG,
    TEAM_NS_TAG,
    admin_endpoint_service_ns_mapper,
    api_endpoint_service_ns_mapper,
    data_admin_maker_ns_mapper,
    endpoint_service_ns_mapper,
    get_endpoint_owner_info,
    get_owner_tags_from_span,
    service_ns_team_mapper,
    workflow_metadata_list,
)


class TestOwnerMappingConfigs(unittest.TestCase):
    def test_get_endpoint_owner_info(self):
        service_ns, team_ns, priority, workflows = get_endpoint_owner_info(
            "non_existent"
        )
        assert service_ns == "none"
        assert team_ns == "none"
        assert priority == "none"
        assert workflows == []

        service_ns, team_ns, priority, workflows = get_endpoint_owner_info(
            "/api/v1/api_key"
        )
        assert service_ns == "authentication"
        assert team_ns == "core_services"
        assert priority == "none"
        assert workflows == []

        # test regex scenarios
        service_ns, team_ns, priority, workflows = get_endpoint_owner_info(
            "/api/v1/non_exist/123456/whatever"
        )
        assert service_ns == "none"
        assert team_ns == "none"
        assert priority == "none"
        assert workflows == []

        service_ns, team_ns, priority, workflows = get_endpoint_owner_info(
            "/api/v1/users/123456/care_team"
        )
        assert service_ns == "care_team"
        assert team_ns == "care_discovery"
        assert priority == "p2"
        assert workflows == ["member_books_video_appointment"]

        service_ns, team_ns, priority, workflows = get_endpoint_owner_info(
            "/api/v1/organizations"
        )
        assert service_ns == "enrollments"
        assert team_ns == "enrollments"
        assert priority == "p2"
        assert workflows == ["register_and_confirm_eligibility"]

    def test_valid_workflows(self):
        for endpoint, value in api_endpoint_service_ns_mapper.items():
            for workflow in value.workflows:
                workflow = workflow.strip()
                self.assertIn(
                    workflow,
                    workflow_metadata_list,
                    f"{workflow} in endpoint {endpoint} is not a valid workflow",
                )

    def test_admin_endpoint_service_ns_mapper_reverse_sort_order(self):
        descending_sorted_admin_endpoint_mapping = sorted(
            admin_endpoint_service_ns_mapper.items(),
            reverse=True,  # expected to be in descending alphabetical order
        )
        mapping_items = list(admin_endpoint_service_ns_mapper.items())
        # written as an explicit loop to make failure cases easily identifiable
        for i, item in enumerate(mapping_items):
            assert item == descending_sorted_admin_endpoint_mapping[i]

    def test_api_endpoint_service_ns_mapper_reverse_sort_order(self):
        descending_sorted_api_endpoint_mapping = sorted(
            api_endpoint_service_ns_mapper.items(),
            reverse=True,  # expected to be in descending alphabetical order
        )
        mapping_items = list(api_endpoint_service_ns_mapper.items())
        # written as an explicit loop to make failure cases easily identifiable
        for i, item in enumerate(mapping_items):
            assert item == descending_sorted_api_endpoint_mapping[i]

    def test_service_ns_team_mapper_reverse_sort_order(self):
        descending_service_ns_team_mapping = sorted(
            service_ns_team_mapper.items(),
            reverse=False,  # expected to be in ascending alphabetical order
        )
        mapping_items = list(service_ns_team_mapper.items())
        # written as an explicit loop to make failure cases easily identifiable
        for i, item in enumerate(mapping_items):
            assert item == descending_service_ns_team_mapping[i]

    def test_get_owner_tags_from_span(self):
        # scenario 1: no active span
        service_ns, team_ns = get_owner_tags_from_span()
        assert service_ns is None
        assert team_ns is None

        # scenario 2: with span
        with tracer.trace("test_span") as span:
            assert tracer.current_span() is span

            service_ns, team_ns = get_owner_tags_from_span()
            assert service_ns is None
            assert team_ns is None

            service_ns, team_ns = get_owner_tags_from_span(span)
            assert service_ns is None
            assert team_ns is None

            span.set_tags(
                {
                    SERVICE_NS_TAG: "sample_service_ns",
                    TEAM_NS_TAG: "sample_team_ns",
                }
            )

            service_ns, team_ns = get_owner_tags_from_span()
            assert service_ns == "sample_service_ns"
            assert team_ns == "sample_team_ns"

            service_ns, team_ns = get_owner_tags_from_span(span)
            assert service_ns == "sample_service_ns"
            assert team_ns == "sample_team_ns"

    def test_inject_service_ns_info(self):
        sample_service_ns = "sample_service_ns"
        sample_team_ns = "sample_team_ns"

        with tracer.trace("test_parent_span") as parent_span:
            assert tracer.current_span() is parent_span

            parent_span.set_tags(
                {
                    SERVICE_NS_TAG: sample_service_ns,
                    TEAM_NS_TAG: sample_team_ns,
                }
            )

            service_ns, team_ns = get_owner_tags_from_span()
            assert service_ns == sample_service_ns
            assert team_ns == sample_team_ns

            service_ns, team_ns = get_owner_tags_from_span(parent_span)
            assert service_ns == sample_service_ns
            assert team_ns == sample_team_ns

            with tracer.trace("test_child_span") as child_span:
                assert tracer.current_span() is child_span

                current_service_ns = child_span.get_tag(SERVICE_NS_TAG)
                current_team_ns = child_span.get_tag(TEAM_NS_TAG)

                assert current_service_ns == sample_service_ns
                assert current_team_ns == sample_team_ns


class TestOwnerMappingsUpToDate:
    # DO NOT ADD NEW UNMAPPED ROUTES
    # PLEASE MAP ALL NEW ROUTES in service_owner_mapper.py
    admin_known_unmapped_routes_set = {
        "/admin/",
        "/admin/actions/add_fee",
        "/admin/actions/appointment_followup_info",
        "/admin/actions/list_all_practitioners/",
        "/admin/actions/payout_reimbursement",
        "/admin/actions/register_user",
        "/admin/actions/reimbursement_cycle_member_credit_transactions/new",
        "/admin/actions/reimbursement_wallet/qle",
        "/admin/actions/replace_practitioner/",
        "/admin/actions/repopulate_braze",
        "/admin/actions/resend_invite",
        "/admin/actions/restart_invoice_transfers",
        "/admin/actions/send_cx_message",
        "/admin/actions/set_promo_time_range",
        "/admin/actions/set_recurring_availability",
        "/admin/actions/start_delete_user_request",
        "/admin/actions/start_invoice_transfers",
        "/admin/actions/translate_stripe_csv",
        "/admin/actions/update_member_bulk_messaging_settings",
        "/admin/actions/update_practitioner_bank_account",
        "/admin/address/",
        "/admin/address/action/",
        "/admin/address/ajax/lookup/",
        "/admin/address/ajax/update/",
        "/admin/address/delete/",
        "/admin/address/details/",
        "/admin/address/edit/",
        "/admin/address/export/(.+?)/",
        "/admin/address/new/",
        "/admin/affected_appointments",
        "/admin/agreement/action/",
        "/admin/agreement/ajax/lookup/",
        "/admin/agreement/ajax/update/",
        "/admin/agreement/delete/",
        "/admin/agreement/details/",
        "/admin/agreement/edit/",
        "/admin/agreement/export/(.+?)/",
        "/admin/agreement/new/",
        "/admin/agreementacceptance/",
        "/admin/agreementacceptance/action/",
        "/admin/agreementacceptance/ajax/lookup/",
        "/admin/agreementacceptance/ajax/update/",
        "/admin/agreementacceptance/delete/",
        "/admin/agreementacceptance/details/",
        "/admin/agreementacceptance/edit/",
        "/admin/agreementacceptance/export/(.+?)/",
        "/admin/agreementacceptance/new/",
        "/admin/answer/",
        "/admin/answer/action/",
        "/admin/answer/ajax/lookup/",
        "/admin/answer/ajax/update/",
        "/admin/answer/delete/",
        "/admin/answer/details/",
        "/admin/answer/edit/",
        "/admin/answer/export/(.+?)/",
        "/admin/answer/new/",
        "/admin/appointment/",
        "/admin/appointment/action/",
        "/admin/appointment/ajax/lookup/",
        "/admin/appointment/ajax/update/",
        "/admin/appointment/cc_dashboard/(.+?)",
        "/admin/appointment/delete/",
        "/admin/appointment/details/",
        "/admin/appointment/edit/",
        "/admin/appointment/export/(.+?)/",
        "/admin/appointment/list_view_appointments",
        "/admin/appointment/new/",
        "/admin/appointmentfeecreator/action/",
        "/admin/appointmentfeecreator/ajax/lookup/",
        "/admin/appointmentfeecreator/ajax/update/",
        "/admin/appointmentfeecreator/delete/",
        "/admin/appointmentfeecreator/details/",
        "/admin/appointmentfeecreator/edit/",
        "/admin/appointmentfeecreator/export/(.+?)/",
        "/admin/appointmentfeecreator/new/",
        "/admin/appointmentmetadata/action/",
        "/admin/appointmentmetadata/ajax/lookup/",
        "/admin/appointmentmetadata/ajax/update/",
        "/admin/appointmentmetadata/delete/",
        "/admin/appointmentmetadata/details/",
        "/admin/appointmentmetadata/export/(.+?)/",
        "/admin/assessment/action/",
        "/admin/assessment/ajax/lookup/",
        "/admin/assessment/ajax/update/",
        "/admin/assessment/delete/",
        "/admin/assessment/details/",
        "/admin/assessment/export/(.+?)/",
        "/admin/assessmentlifecycle/action/",
        "/admin/assessmentlifecycle/ajax/lookup/",
        "/admin/assessmentlifecycle/ajax/update/",
        "/admin/assessmentlifecycle/delete/",
        "/admin/assessmentlifecycle/details/",
        "/admin/assessmentlifecycle/edit/",
        "/admin/assessmentlifecycle/export/(.+?)/",
        "/admin/assessmentlifecycle/new/",
        "/admin/assessmenttrack/action/",
        "/admin/assessmenttrack/ajax/lookup/",
        "/admin/assessmenttrack/ajax/update/",
        "/admin/assessmenttrack/delete/",
        "/admin/assessmenttrack/details/",
        "/admin/assessmenttrack/edit/",
        "/admin/assessmenttrack/export/(.+?)/",
        "/admin/assignable-advocates/(.+?)/matching-rule-set",
        "/admin/assignable-advocates/(.+?)/matching-rule-set/(.+?)",
        "/admin/assignableadvocate/action/",
        "/admin/assignableadvocate/ajax/lookup/",
        "/admin/assignableadvocate/ajax/update/",
        "/admin/assignableadvocate/delete/",
        "/admin/assignableadvocate/details/",
        "/admin/assignableadvocate/export/(.+?)/",
        "/admin/automaticcodeapplication/",
        "/admin/automaticcodeapplication/action/",
        "/admin/automaticcodeapplication/ajax/lookup/",
        "/admin/automaticcodeapplication/ajax/update/",
        "/admin/automaticcodeapplication/delete/",
        "/admin/automaticcodeapplication/details/",
        "/admin/automaticcodeapplication/edit/",
        "/admin/automaticcodeapplication/export/(.+?)/",
        "/admin/automaticcodeapplication/new/",
        "/admin/availabilitynotificationrequest/",
        "/admin/availabilitynotificationrequest/action/",
        "/admin/availabilitynotificationrequest/ajax/lookup/",
        "/admin/availabilitynotificationrequest/ajax/update/",
        "/admin/availabilitynotificationrequest/delete/",
        "/admin/availabilitynotificationrequest/details/",
        "/admin/availabilitynotificationrequest/edit/",
        "/admin/availabilitynotificationrequest/export/(.+?)/",
        "/admin/availabilitynotificationrequest/new/",
        "/admin/blockedphonenumber/",
        "/admin/blockedphonenumber/action/",
        "/admin/blockedphonenumber/ajax/lookup/",
        "/admin/blockedphonenumber/ajax/update/",
        "/admin/blockedphonenumber/delete/",
        "/admin/blockedphonenumber/details/",
        "/admin/blockedphonenumber/edit/",
        "/admin/blockedphonenumber/export/(.+?)/",
        "/admin/blockedphonenumber/new/",
        "/admin/bulk_practitioner_mfa_tools",
        "/admin/businesslead/",
        "/admin/businesslead/action/",
        "/admin/businesslead/ajax/lookup/",
        "/admin/businesslead/ajax/update/",
        "/admin/businesslead/delete/",
        "/admin/businesslead/details/",
        "/admin/businesslead/edit/",
        "/admin/businesslead/export/(.+?)/",
        "/admin/businesslead/new/",
        "/admin/ca_member_transition_templates/",
        "/admin/ca_member_transition_templates/action/",
        "/admin/ca_member_transition_templates/ajax/lookup/",
        "/admin/ca_member_transition_templates/ajax/update/",
        "/admin/ca_member_transition_templates/delete/",
        "/admin/ca_member_transition_templates/details/",
        "/admin/ca_member_transition_templates/export/(.+?)/",
        "/admin/ca_member_transition_templates/new/",
        "/admin/ca_member_transitions/transition_logs/delete",
        "/admin/ca_member_transitions/transition_logs/download_csv/(.+?)",
        "/admin/care_team_control_center/global_max_capacity",
        "/admin/careprogram/",
        "/admin/careprogram/action/",
        "/admin/careprogram/ajax/lookup/",
        "/admin/careprogram/ajax/update/",
        "/admin/careprogram/delete/",
        "/admin/careprogram/details/",
        "/admin/careprogram/edit/",
        "/admin/careprogram/export/(.+?)/",
        "/admin/careprogram/new/",
        "/admin/category/action/",
        "/admin/category/ajax/lookup/",
        "/admin/category/ajax/update/",
        "/admin/category/delete/",
        "/admin/category/details/",
        "/admin/category/export/(.+?)/",
        "/admin/categoryversion/action/",
        "/admin/categoryversion/ajax/lookup/",
        "/admin/categoryversion/ajax/update/",
        "/admin/categoryversion/delete/",
        "/admin/categoryversion/details/",
        "/admin/categoryversion/edit/",
        "/admin/categoryversion/export/(.+?)/",
        "/admin/categoryversion/new/",
        "/admin/certification/",
        "/admin/certification/action/",
        "/admin/certification/ajax/lookup/",
        "/admin/certification/ajax/update/",
        "/admin/certification/delete/",
        "/admin/certification/details/",
        "/admin/certification/edit/",
        "/admin/certification/export/(.+?)/",
        "/admin/certification/new/",
        "/admin/characteristic/",
        "/admin/characteristic/action/",
        "/admin/characteristic/ajax/lookup/",
        "/admin/characteristic/ajax/update/",
        "/admin/characteristic/delete/",
        "/admin/characteristic/details/",
        "/admin/characteristic/edit/",
        "/admin/characteristic/export/(.+?)/",
        "/admin/characteristic/new/",
        "/admin/clienttrack/action/",
        "/admin/clienttrack/ajax/lookup/",
        "/admin/clienttrack/ajax/update/",
        "/admin/clienttrack/delete/",
        "/admin/clienttrack/edit/",
        "/admin/clienttrack/export/(.+?)/",
        "/admin/clienttrack/new/",
        "/admin/connectedcontentfield/action/",
        "/admin/connectedcontentfield/ajax/lookup/",
        "/admin/connectedcontentfield/ajax/update/",
        "/admin/connectedcontentfield/delete/",
        "/admin/connectedcontentfield/details/",
        "/admin/connectedcontentfield/edit/",
        "/admin/connectedcontentfield/export/(.+?)/",
        "/admin/connectedcontentfield/new/",
        "/admin/credit/",
        "/admin/credit/action/",
        "/admin/credit/ajax/lookup/",
        "/admin/credit/ajax/update/",
        "/admin/credit/delete/",
        "/admin/credit/details/",
        "/admin/credit/edit/",
        "/admin/credit/export/(.+?)/",
        "/admin/credit/new/",
        "/admin/delete_user",
        "/admin/device/",
        "/admin/device/action/",
        "/admin/device/ajax/lookup/",
        "/admin/device/ajax/update/",
        "/admin/device/delete/",
        "/admin/device/details/",
        "/admin/device/edit/",
        "/admin/device/export/(.+?)/",
        "/admin/device/new/",
        "/admin/enrollment/action/",
        "/admin/enrollment/ajax/lookup/",
        "/admin/enrollment/ajax/update/",
        "/admin/enrollment/delete/",
        "/admin/enrollment/details/",
        "/admin/enrollment/edit/",
        "/admin/enrollment/export/(.+?)/",
        "/admin/enrollment/new/",
        "/admin/enterprise_setup",
        "/admin/enterprise_setup/",
        "/admin/enterprise_setup/enroll_track",
        "/admin/enterprise_setup/msft_setup",
        "/admin/enterprise_setup_confirm",
        "/admin/externalidentity/",
        "/admin/externalidentity/action/",
        "/admin/externalidentity/ajax/lookup/",
        "/admin/externalidentity/ajax/update/",
        "/admin/externalidentity/delete/",
        "/admin/externalidentity/details/",
        "/admin/externalidentity/edit/",
        "/admin/externalidentity/export/(.+?)/",
        "/admin/externalidentity/new/",
        "/admin/fastfind",
        "/admin/feeaccountingentry/action/",
        "/admin/feeaccountingentry/ajax/lookup/",
        "/admin/feeaccountingentry/delete/",
        "/admin/feeaccountingentry/details/",
        "/admin/feeaccountingentry/export/(.+?)/",
        "/admin/feeaccountingentry/new/",
        "/admin/forumban/",
        "/admin/forumban/action/",
        "/admin/forumban/ajax/lookup/",
        "/admin/forumban/ajax/update/",
        "/admin/forumban/delete/",
        "/admin/forumban/details/",
        "/admin/forumban/edit/",
        "/admin/forumban/export/(.+?)/",
        "/admin/forumban/new/",
        "/admin/high_risk_dashboard/",
        "/admin/high_risk_dashboard/action/",
        "/admin/high_risk_dashboard/ajax/lookup/",
        "/admin/high_risk_dashboard/ajax/update/",
        "/admin/high_risk_dashboard/delete/",
        "/admin/high_risk_dashboard/details/",
        "/admin/high_risk_dashboard/edit/",
        "/admin/high_risk_dashboard/export/(.+?)/",
        "/admin/high_risk_dashboard/new/",
        "/admin/identityprovider/",
        "/admin/identityprovider/action/",
        "/admin/identityprovider/ajax/lookup/",
        "/admin/identityprovider/ajax/update/",
        "/admin/identityprovider/delete/",
        "/admin/identityprovider/details/",
        "/admin/identityprovider/edit/",
        "/admin/identityprovider/export/(.+?)/",
        "/admin/identityprovider/new/",
        "/admin/identityproviderfieldalias/",
        "/admin/identityproviderfieldalias/action/",
        "/admin/identityproviderfieldalias/ajax/lookup/",
        "/admin/identityproviderfieldalias/ajax/update/",
        "/admin/identityproviderfieldalias/delete/",
        "/admin/identityproviderfieldalias/details/",
        "/admin/identityproviderfieldalias/edit/",
        "/admin/identityproviderfieldalias/export/(.+?)/",
        "/admin/identityproviderfieldalias/new/",
        "/admin/in_state_match/",
        "/admin/in_state_match/action/",
        "/admin/in_state_match/ajax/lookup/",
        "/admin/in_state_match/ajax/update/",
        "/admin/in_state_match/delete/",
        "/admin/in_state_match/details/",
        "/admin/in_state_match/edit/",
        "/admin/in_state_match/export/(.+?)/",
        "/admin/in_state_match/new/",
        "/admin/incentivepayment/",
        "/admin/incentivepayment/action/",
        "/admin/incentivepayment/ajax/lookup/",
        "/admin/incentivepayment/ajax/update/",
        "/admin/incentivepayment/delete/",
        "/admin/incentivepayment/details/",
        "/admin/incentivepayment/edit/",
        "/admin/incentivepayment/export/(.+?)/",
        "/admin/incentivepayment/new/",
        "/admin/invite/action/",
        "/admin/invite/ajax/lookup/",
        "/admin/invite/ajax/update/",
        "/admin/invite/delete/",
        "/admin/invite/details/",
        "/admin/invite/export/(.+?)/",
        "/admin/invite/new/",
        "/admin/invoice/action/",
        "/admin/invoice/ajax/lookup/",
        "/admin/invoice/ajax/update/",
        "/admin/invoice/close/",
        "/admin/invoice/delete/",
        "/admin/invoice/details/",
        "/admin/invoice/export/(.+?)/",
        "/admin/invoice/new/",
        "/admin/iosnondeeplinkurl/",
        "/admin/iosnondeeplinkurl/action/",
        "/admin/iosnondeeplinkurl/ajax/lookup/",
        "/admin/iosnondeeplinkurl/ajax/update/",
        "/admin/iosnondeeplinkurl/delete/",
        "/admin/iosnondeeplinkurl/details/",
        "/admin/iosnondeeplinkurl/edit/",
        "/admin/iosnondeeplinkurl/export/(.+?)/",
        "/admin/iosnondeeplinkurl/new/",
        "/admin/language/",
        "/admin/language/action/",
        "/admin/language/ajax/lookup/",
        "/admin/language/ajax/update/",
        "/admin/language/delete/",
        "/admin/language/details/",
        "/admin/language/edit/",
        "/admin/language/export/(.+?)/",
        "/admin/language/new/",
        "/admin/logging/",
        "/admin/login/",
        "/admin/logout/",
        "/admin/marketing_tools",
        "/admin/me",
        "/admin/medication/",
        "/admin/medication/action/",
        "/admin/medication/ajax/lookup/",
        "/admin/medication/ajax/update/",
        "/admin/medication/delete/",
        "/admin/medication/details/",
        "/admin/medication/edit/",
        "/admin/medication/export/(.+?)/",
        "/admin/medication/new/",
        "/admin/memberpractitionerassociation/action/",
        "/admin/memberpractitionerassociation/ajax/update/",
        "/admin/memberpractitionerassociation/delete/",
        "/admin/memberpractitionerassociation/details/",
        "/admin/memberpractitionerassociation/export/(.+?)/",
        "/admin/memberprofile/action/",
        "/admin/memberprofile/ajax/lookup/",
        "/admin/memberprofile/ajax/update/",
        "/admin/memberprofile/delete/",
        "/admin/memberprofile/details/",
        "/admin/memberprofile/export/(.+?)/",
        "/admin/memberriskflag/action/",
        "/admin/memberriskflag/ajax/lookup/",
        "/admin/memberriskflag/ajax/update/",
        "/admin/memberriskflag/delete/",
        "/admin/memberriskflag/details/",
        "/admin/memberriskflag/edit/",
        "/admin/memberriskflag/export/(.+?)/",
        "/admin/memberriskflag/new/",
        "/admin/membertrack/ajax/update/",
        "/admin/membertrack/delete/",
        "/admin/membertrack/details/",
        "/admin/membertrack/export/(.+?)/",
        "/admin/membertrack/new/",
        "/admin/message/",
        "/admin/message/action/",
        "/admin/message/ajax/lookup/",
        "/admin/message/ajax/update/",
        "/admin/message/delete/",
        "/admin/message/details/",
        "/admin/message/edit/",
        "/admin/message/export/(.+?)/",
        "/admin/message/new/",
        "/admin/messagebilling/",
        "/admin/messagebilling/action/",
        "/admin/messagebilling/ajax/lookup/",
        "/admin/messagebilling/ajax/update/",
        "/admin/messagebilling/delete/",
        "/admin/messagebilling/details/",
        "/admin/messagebilling/edit/",
        "/admin/messagebilling/export/(.+?)/",
        "/admin/messagebilling/new/",
        "/admin/messagecredit/",
        "/admin/messagecredit/action/",
        "/admin/messagecredit/ajax/lookup/",
        "/admin/messagecredit/ajax/update/",
        "/admin/messagecredit/delete/",
        "/admin/messagecredit/details/",
        "/admin/messagecredit/edit/",
        "/admin/messagecredit/export/(.+?)/",
        "/admin/messagecredit/new/",
        "/admin/messageproduct/",
        "/admin/messageproduct/action/",
        "/admin/messageproduct/ajax/lookup/",
        "/admin/messageproduct/ajax/update/",
        "/admin/messageproduct/delete/",
        "/admin/messageproduct/details/",
        "/admin/messageproduct/edit/",
        "/admin/messageproduct/export/(.+?)/",
        "/admin/messageproduct/new/",
        "/admin/module/",
        "/admin/module/action/",
        "/admin/module/ajax/lookup/",
        "/admin/module/ajax/update/",
        "/admin/module/delete/",
        "/admin/module/details/",
        "/admin/module/edit/",
        "/admin/module/export/(.+?)/",
        "/admin/module/new/",
        "/admin/need/",
        "/admin/need/action/",
        "/admin/need/ajax/lookup/",
        "/admin/need/ajax/update/",
        "/admin/need/bookable_times/",
        "/admin/need/delete/",
        "/admin/need/details/",
        "/admin/need/edit/",
        "/admin/need/export/(.+?)/",
        "/admin/need/new/",
        "/admin/need/products/",
        "/admin/need/state-match-not-permissible/",
        "/admin/need/update/",
        "/admin/needcategory/",
        "/admin/needcategory/action/",
        "/admin/needcategory/ajax/lookup/",
        "/admin/needcategory/ajax/update/",
        "/admin/needcategory/bookable_times/",
        "/admin/needcategory/delete/",
        "/admin/needcategory/details/",
        "/admin/needcategory/edit/",
        "/admin/needcategory/export/(.+?)/",
        "/admin/needcategory/new/",
        "/admin/needcategory/products/",
        "/admin/needcategory/state-match-not-permissible/",
        "/admin/needcategory/update/",
        "/admin/needsassessment/action/",
        "/admin/needsassessment/ajax/lookup/",
        "/admin/needsassessment/ajax/update/",
        "/admin/needsassessment/delete/",
        "/admin/needsassessment/details/",
        "/admin/needsassessment/export/(.+?)/",
        "/admin/needsassessment/new/",
        "/admin/organization/",
        "/admin/organization/action/",
        "/admin/organization/ajax/lookup/",
        "/admin/organization/ajax/update/",
        "/admin/organization/delete/",
        "/admin/organization/details/",
        "/admin/organization/edit/",
        "/admin/organization/export/(.+?)/",
        "/admin/organization/new/",
        "/admin/organizationeligibilityfield/",
        "/admin/organizationeligibilityfield/action/",
        "/admin/organizationeligibilityfield/ajax/lookup/",
        "/admin/organizationeligibilityfield/ajax/update/",
        "/admin/organizationeligibilityfield/delete/",
        "/admin/organizationeligibilityfield/details/",
        "/admin/organizationeligibilityfield/edit/",
        "/admin/organizationeligibilityfield/export/(.+?)/",
        "/admin/organizationeligibilityfield/new/",
        "/admin/organizationemaildomain/",
        "/admin/organizationemaildomain/action/",
        "/admin/organizationemaildomain/ajax/lookup/",
        "/admin/organizationemaildomain/ajax/update/",
        "/admin/organizationemaildomain/delete/",
        "/admin/organizationemaildomain/details/",
        "/admin/organizationemaildomain/edit/",
        "/admin/organizationemaildomain/export/(.+?)/",
        "/admin/organizationemaildomain/new/",
        "/admin/organizationemployee/action/",
        "/admin/organizationemployee/ajax/update/",
        "/admin/organizationemployee/delete/",
        "/admin/organizationemployee/export/(.+?)/",
        "/admin/organizationemployeedependent/action/",
        "/admin/organizationemployeedependent/ajax/lookup/",
        "/admin/organizationemployeedependent/ajax/update/",
        "/admin/organizationemployeedependent/delete/",
        "/admin/organizationemployeedependent/details/",
        "/admin/organizationemployeedependent/export/(.+?)/",
        "/admin/organizationemployeedependent/new/",
        "/admin/organizationmoduleextension/",
        "/admin/organizationmoduleextension/action/",
        "/admin/organizationmoduleextension/ajax/lookup/",
        "/admin/organizationmoduleextension/ajax/update/",
        "/admin/organizationmoduleextension/delete/",
        "/admin/organizationmoduleextension/details/",
        "/admin/organizationmoduleextension/edit/",
        "/admin/organizationmoduleextension/export/(.+?)/",
        "/admin/organizationmoduleextension/new/",
        "/admin/paymentaccountingentry/",
        "/admin/paymentaccountingentry/action/",
        "/admin/paymentaccountingentry/ajax/lookup/",
        "/admin/paymentaccountingentry/ajax/update/",
        "/admin/paymentaccountingentry/delete/",
        "/admin/paymentaccountingentry/details/",
        "/admin/paymentaccountingentry/edit/",
        "/admin/paymentaccountingentry/export/(.+?)/",
        "/admin/paymentaccountingentry/new/",
        "/admin/phase/",
        "/admin/phase/action/",
        "/admin/phase/ajax/lookup/",
        "/admin/phase/ajax/update/",
        "/admin/phase/delete/",
        "/admin/phase/details/",
        "/admin/phase/edit/",
        "/admin/phase/export/(.+?)/",
        "/admin/phase/new/",
        "/admin/populartopic/action/",
        "/admin/populartopic/ajax/lookup/",
        "/admin/populartopic/ajax/update/",
        "/admin/populartopic/delete/",
        "/admin/populartopic/details/",
        "/admin/populartopic/edit/",
        "/admin/populartopic/export/(.+?)/",
        "/admin/populartopic/new/",
        "/admin/post/action/",
        "/admin/post/ajax/lookup/",
        "/admin/post/ajax/update/",
        "/admin/post/delete/",
        "/admin/post/details/",
        "/admin/post/export/(.+?)/",
        "/admin/post/new/",
        "/admin/practitioner_management/delete_fees",
        "/admin/practitioner_management/disable_mfa",
        "/admin/practitioner_management/enable_mfa",
        "/admin/practitioner_tools",
        "/admin/practitionerappointmentack/",
        "/admin/practitionerappointmentack/action/",
        "/admin/practitionerappointmentack/ajax/lookup/",
        "/admin/practitionerappointmentack/ajax/update/",
        "/admin/practitionerappointmentack/delete/",
        "/admin/practitionerappointmentack/details/",
        "/admin/practitionerappointmentack/edit/",
        "/admin/practitionerappointmentack/export/(.+?)/",
        "/admin/practitionerappointmentack/new/",
        "/admin/practitionerinvite/",
        "/admin/practitionerinvite/action/",
        "/admin/practitionerinvite/ajax/lookup/",
        "/admin/practitionerinvite/ajax/update/",
        "/admin/practitionerinvite/delete/",
        "/admin/practitionerinvite/details/",
        "/admin/practitionerinvite/edit/",
        "/admin/practitionerinvite/export/(.+?)/",
        "/admin/practitionerinvite/new/",
        "/admin/practitionerprofile/",
        "/admin/practitionerprofile/action/",
        "/admin/practitionerprofile/ajax/lookup/",
        "/admin/practitionerprofile/ajax/update/",
        "/admin/practitionerprofile/delete/",
        "/admin/practitionerprofile/details/",
        "/admin/practitionerprofile/edit/",
        "/admin/practitionerprofile/export/(.+?)/",
        "/admin/practitionerprofile/list/",
        "/admin/practitionerprofile/list_view_practitioners",
        "/admin/practitionerprofile/new/",
        "/admin/practitionerprofile/new_time_zone",
        "/admin/practitionerprofile/products/",
        "/admin/practitionerprofile/state-match-not-permissible/",
        "/admin/practitionerprofile/update/",
        "/admin/practitionertrackvgc/ajax/update/",
        "/admin/practitionertrackvgc/delete/",
        "/admin/practitionertrackvgc/edit/",
        "/admin/practitionertrackvgc/export/(.+?)/",
        "/admin/product/",
        "/admin/product/action/",
        "/admin/product/ajax/lookup/",
        "/admin/product/ajax/update/",
        "/admin/product/delete/",
        "/admin/product/details/",
        "/admin/product/edit/",
        "/admin/product/export/(.+?)/",
        "/admin/product/new/",
        "/admin/qr/",
        "/admin/question/",
        "/admin/question/action/",
        "/admin/question/ajax/lookup/",
        "/admin/question/ajax/update/",
        "/admin/question/delete/",
        "/admin/question/details/",
        "/admin/question/edit/",
        "/admin/question/export/(.+?)/",
        "/admin/question/new/",
        "/admin/questionnaire/",
        "/admin/questionnaire/action/",
        "/admin/questionnaire/ajax/lookup/",
        "/admin/questionnaire/ajax/update/",
        "/admin/questionnaire/delete/",
        "/admin/questionnaire/details/",
        "/admin/questionnaire/edit/",
        "/admin/questionnaire/export/(.+?)/",
        "/admin/questionnaire/new/",
        "/admin/questionset/",
        "/admin/questionset/action/",
        "/admin/questionset/ajax/lookup/",
        "/admin/questionset/ajax/update/",
        "/admin/questionset/delete/",
        "/admin/questionset/details/",
        "/admin/questionset/edit/",
        "/admin/questionset/export/(.+?)/",
        "/admin/questionset/new/",
        "/admin/rbac/bulk_insert",
        "/admin/recordedanswerset/",
        "/admin/recordedanswerset/action/",
        "/admin/recordedanswerset/ajax/lookup/",
        "/admin/recordedanswerset/ajax/update/",
        "/admin/recordedanswerset/delete/",
        "/admin/recordedanswerset/details/",
        "/admin/recordedanswerset/edit/",
        "/admin/recordedanswerset/export/(.+?)/",
        "/admin/recordedanswerset/new/",
        "/admin/referralcode/",
        "/admin/referralcode/action/",
        "/admin/referralcode/ajax/lookup/",
        "/admin/referralcode/ajax/update/",
        "/admin/referralcode/delete/",
        "/admin/referralcode/details/",
        "/admin/referralcode/edit/",
        "/admin/referralcode/export/(.+?)/",
        "/admin/referralcode/new/",
        "/admin/referralcodecategory/",
        "/admin/referralcodecategory/action/",
        "/admin/referralcodecategory/ajax/lookup/",
        "/admin/referralcodecategory/ajax/update/",
        "/admin/referralcodecategory/delete/",
        "/admin/referralcodecategory/details/",
        "/admin/referralcodecategory/edit/",
        "/admin/referralcodecategory/export/(.+?)/",
        "/admin/referralcodecategory/new/",
        "/admin/referralcodesubcategory/",
        "/admin/referralcodesubcategory/action/",
        "/admin/referralcodesubcategory/ajax/lookup/",
        "/admin/referralcodesubcategory/ajax/update/",
        "/admin/referralcodesubcategory/delete/",
        "/admin/referralcodesubcategory/details/",
        "/admin/referralcodesubcategory/edit/",
        "/admin/referralcodesubcategory/export/(.+?)/",
        "/admin/referralcodesubcategory/new/",
        "/admin/reporting/appointments",
        "/admin/reporting/fees",
        "/admin/reporting/invoices",
        "/admin/reporting/invoices/all",
        "/admin/reporting/messaging",
        "/admin/resource/action/",
        "/admin/resource/ajax/lookup/",
        "/admin/resource/ajax/update/",
        "/admin/resource/delete/",
        "/admin/resource/details/",
        "/admin/resource/export/(.+?)/",
        "/admin/resourcefeaturedclasstrackphase/",
        "/admin/resourcefeaturedclasstrackphase/action/",
        "/admin/resourcefeaturedclasstrackphase/ajax/lookup/",
        "/admin/resourcefeaturedclasstrackphase/ajax/update/",
        "/admin/resourcefeaturedclasstrackphase/delete/",
        "/admin/resourcefeaturedclasstrackphase/details/",
        "/admin/resourcefeaturedclasstrackphase/edit/",
        "/admin/resourcefeaturedclasstrackphase/export/(.+?)/",
        "/admin/resourcefeaturedclasstrackphase/new/",
        "/admin/riskflag/action/",
        "/admin/riskflag/ajax/lookup/",
        "/admin/riskflag/ajax/update/",
        "/admin/riskflag/delete/",
        "/admin/riskflag/details/",
        "/admin/riskflag/edit/",
        "/admin/riskflag/export/(.+?)/",
        "/admin/riskflag/new/",
        "/admin/role/",
        "/admin/role/action/",
        "/admin/role/ajax/lookup/",
        "/admin/role/ajax/update/",
        "/admin/role/delete/",
        "/admin/role/details/",
        "/admin/role/edit/",
        "/admin/role/export/(.+?)/",
        "/admin/role/new/",
        "/admin/roleprofile/",
        "/admin/roleprofile/action/",
        "/admin/roleprofile/ajax/lookup/",
        "/admin/roleprofile/ajax/update/",
        "/admin/roleprofile/delete/",
        "/admin/roleprofile/details/",
        "/admin/roleprofile/edit/",
        "/admin/roleprofile/export/(.+?)/",
        "/admin/roleprofile/new/",
        "/admin/rq/",
        "/admin/rq/(.+?)",
        "/admin/rq/(.+?)/",
        "/admin/rq/(.+?)/(.+?)",
        "/admin/rq/(.+?)/data/job/(.+?).json",
        "/admin/rq/(.+?)/data/jobs/(.+?)/(.+?)/(.+?)/(.+?).json",
        "/admin/rq/(.+?)/data/queues.json",
        "/admin/rq/(.+?)/data/workers.json",
        "/admin/rq/(.+?)/view",
        "/admin/rq/(.+?)/view/job/(.+?)",
        "/admin/rq/(.+?)/view/jobs",
        "/admin/rq/(.+?)/view/jobs/(.+?)/(.+?)/(.+?)/(.+?)",
        "/admin/rq/(.+?)/view/queues",
        "/admin/rq/(.+?)/view/workers",
        "/admin/rq/favicon.ico",
        "/admin/rq/job/(.+?)/cancel",
        "/admin/rq/job/(.+?)/delete",
        "/admin/rq/job/(.+?)/requeue",
        "/admin/rq/jobs/(.+?)/(.+?).json",
        "/admin/rq/queue/(.+?)/compact",
        "/admin/rq/queue/(.+?)/empty",
        "/admin/rq/queue/(.+?)/(.+?)/empty",
        "/admin/rq/queues.json",
        "/admin/rq/requeue/(.+?)",
        "/admin/rq/requeue-all",
        "/admin/rq/rq-instance/(.+?)",
        "/admin/rq/rq-instances.json",
        "/admin/rq/static/(.+?)",
        "/admin/rq/workers.json",
        "/admin/scheduledmaintenance/",
        "/admin/scheduledmaintenance/action/",
        "/admin/scheduledmaintenance/ajax/lookup/",
        "/admin/scheduledmaintenance/ajax/update/",
        "/admin/scheduledmaintenance/delete/",
        "/admin/scheduledmaintenance/details/",
        "/admin/scheduledmaintenance/edit/",
        "/admin/scheduledmaintenance/export/(.+?)/",
        "/admin/scheduledmaintenance/new/",
        "/admin/scheduleevent/",
        "/admin/scheduleevent/action/",
        "/admin/scheduleevent/ajax/lookup/",
        "/admin/scheduleevent/ajax/update/",
        "/admin/scheduleevent/delete/",
        "/admin/scheduleevent/details/",
        "/admin/scheduleevent/edit/",
        "/admin/scheduleevent/export/(.+?)/",
        "/admin/scheduleevent/new/",
        "/admin/service_metrics",
        "/admin/service_metrics/metric",
        "/admin/specialty-practitioners/bulk-action",
        "/admin/specialty/",
        "/admin/specialty/action/",
        "/admin/specialty/ajax/lookup/",
        "/admin/specialty/ajax/update/",
        "/admin/specialty/delete/",
        "/admin/specialty/details/",
        "/admin/specialty/edit/",
        "/admin/specialty/export/(.+?)/",
        "/admin/specialty/new/",
        "/admin/specialtykeyword/",
        "/admin/specialtykeyword/action/",
        "/admin/specialtykeyword/ajax/lookup/",
        "/admin/specialtykeyword/ajax/update/",
        "/admin/specialtykeyword/delete/",
        "/admin/specialtykeyword/details/",
        "/admin/specialtykeyword/edit/",
        "/admin/specialtykeyword/export/(.+?)/",
        "/admin/specialtykeyword/new/",
        "/admin/static/(.+?)",
        "/admin/survey_responses",
        "/admin/tag/",
        "/admin/tag/action/",
        "/admin/tag/ajax/lookup/",
        "/admin/tag/ajax/update/",
        "/admin/tag/delete/",
        "/admin/tag/details/",
        "/admin/tag/edit/",
        "/admin/tag/export/(.+?)/",
        "/admin/tag/new/",
        "/admin/textcopy/",
        "/admin/textcopy/action/",
        "/admin/textcopy/ajax/lookup/",
        "/admin/textcopy/ajax/update/",
        "/admin/textcopy/delete/",
        "/admin/textcopy/details/",
        "/admin/textcopy/edit/",
        "/admin/textcopy/export/(.+?)/",
        "/admin/textcopy/new/",
        "/admin/urlredirect/",
        "/admin/urlredirect/action/",
        "/admin/urlredirect/ajax/lookup/",
        "/admin/urlredirect/ajax/update/",
        "/admin/urlredirect/delete/",
        "/admin/urlredirect/details/",
        "/admin/urlredirect/edit/",
        "/admin/urlredirect/export/(.+?)/",
        "/admin/urlredirect/new/",
        "/admin/urlredirectpath/",
        "/admin/urlredirectpath/action/",
        "/admin/urlredirectpath/ajax/lookup/",
        "/admin/urlredirectpath/ajax/update/",
        "/admin/urlredirectpath/delete/",
        "/admin/urlredirectpath/details/",
        "/admin/urlredirectpath/edit/",
        "/admin/urlredirectpath/export/(.+?)/",
        "/admin/urlredirectpath/new/",
        "/admin/user/",
        "/admin/user/action/",
        "/admin/user/ajax/lookup/",
        "/admin/user/ajax/update/",
        "/admin/user/delete/",
        "/admin/user/details/",
        "/admin/user/edit/",
        "/admin/user/export/(.+?)/",
        "/admin/user/new/",
        "/admin/userasset/",
        "/admin/userasset/action/",
        "/admin/userasset/ajax/lookup/",
        "/admin/userasset/ajax/update/",
        "/admin/userasset/delete/",
        "/admin/userasset/details/",
        "/admin/userasset/edit/",
        "/admin/userasset/export/(.+?)/",
        "/admin/userasset/new/",
        "/admin/userauth/",
        "/admin/userauth/action/",
        "/admin/userauth/ajax/lookup/",
        "/admin/userauth/ajax/update/",
        "/admin/userauth/delete/",
        "/admin/userauth/details/",
        "/admin/userauth/edit/",
        "/admin/userauth/export/(.+?)/",
        "/admin/userauth/new/",
        "/admin/userexternalidentity/",
        "/admin/userexternalidentity/action/",
        "/admin/userexternalidentity/ajax/lookup/",
        "/admin/userexternalidentity/ajax/update/",
        "/admin/userexternalidentity/delete/",
        "/admin/userexternalidentity/details/",
        "/admin/userexternalidentity/edit/",
        "/admin/userexternalidentity/export/(.+?)/",
        "/admin/userexternalidentity/new/",
        "/admin/userorganizationemployee/action/",
        "/admin/userorganizationemployee/ajax/lookup/",
        "/admin/userorganizationemployee/ajax/update/",
        "/admin/userorganizationemployee/delete/",
        "/admin/userorganizationemployee/details/",
        "/admin/userorganizationemployee/export/(.+?)/",
        "/admin/userorganizationemployee/new/",
        "/admin/vertical/",
        "/admin/vertical/action/",
        "/admin/vertical/ajax/lookup/",
        "/admin/vertical/ajax/update/",
        "/admin/vertical/create_products/",
        "/admin/vertical/deactivate_products/",
        "/admin/vertical/delete/",
        "/admin/vertical/details/",
        "/admin/vertical/edit/",
        "/admin/vertical/export/(.+?)/",
        "/admin/vertical/new/",
        "/admin/verticalgroup/action/",
        "/admin/verticalgroup/ajax/lookup/",
        "/admin/verticalgroup/ajax/update/",
        "/admin/verticalgroup/delete/",
        "/admin/verticalgroup/details/",
        "/admin/verticalgroup/export/(.+?)/",
        "/admin/verticalgroupversion/action/",
        "/admin/verticalgroupversion/ajax/lookup/",
        "/admin/verticalgroupversion/ajax/update/",
        "/admin/verticalgroupversion/delete/",
        "/admin/verticalgroupversion/details/",
        "/admin/verticalgroupversion/edit/",
        "/admin/verticalgroupversion/export/(.+?)/",
        "/admin/verticalgroupversion/new/",
        "/admin/virtualevent/action/",
        "/admin/virtualevent/ajax/lookup/",
        "/admin/virtualevent/ajax/update/",
        "/admin/virtualevent/delete/",
        "/admin/virtualevent/details/",
        "/admin/virtualevent/export/(.+?)/",
        "/admin/virtualeventcategory/",
        "/admin/virtualeventcategory/action/",
        "/admin/virtualeventcategory/ajax/lookup/",
        "/admin/virtualeventcategory/ajax/update/",
        "/admin/virtualeventcategory/delete/",
        "/admin/virtualeventcategory/details/",
        "/admin/virtualeventcategory/edit/",
        "/admin/virtualeventcategory/export/(.+?)/",
        "/admin/virtualeventcategory/new/",
        "/admin/virtualeventcategorytrack/",
        "/admin/virtualeventcategorytrack/action/",
        "/admin/virtualeventcategorytrack/ajax/lookup/",
        "/admin/virtualeventcategorytrack/ajax/update/",
        "/admin/virtualeventcategorytrack/delete/",
        "/admin/virtualeventcategorytrack/details/",
        "/admin/virtualeventcategorytrack/edit/",
        "/admin/virtualeventcategorytrack/export/(.+?)/",
        "/admin/virtualeventcategorytrack/new/",
        "/admin/wallet_tools/create_employer_configurations",
        "/admin/wallet_tools/download_org_config_zip",
        "/admin/wallet_tools/employer_direct_billing_account",
        "/admin/wallet_tools/handle_smp_rx_file_audit",
        "/admin/wallet_tools/reconciliation_report",
        "/admin/wallet_tools/us_fertility_reconciliation_report",
        "/admin/wallet_tools/wallet_client_report_reimbursements_audit",
        "/eligibility-admin/",
        "/eligibility-admin/(.+?)",
        "/static/(.+?)",
        "/api/readyz",
        "/api/livez",
        "/api/startupz",
        "/readyz",
        "/livez",
        "/startupz",
    }
    api_known_unmapped_routes_set = {
        # System APIs
        "/livez",
        "/readyz",
        "/startupz",
        "/api/livez",
        "/api/readyz",
        "/api/startupz",
        # TODO: add deprecated decorator for these APIs
        # Deprecated
        "/static/(.+?)",
        "/api/v1/users/(.+?)/dashboard",
        "/api/v1/users/(.+?)/dismissals",
        "/api/v1/_/ios_non_deeplink_urls",
        "/api/v1/_/agreements/subscription/(.+?)",
        "/api/v1/users/(.+?)/transitions/programs",
        "/api/v1/users/life_stages",
        # Maybe deprecated
        "/api/v1/medications",
        "/api/v1/vendor/mat/webhooks",
        "/api/v1/_/mail_biz_lead",
        "/api/v1/users/(.+?)/prompt",
        # Unmapped
        "/api/v1/users/(.+?)/files",
        "/api/v1/cancellation_policies",
    }
    known_unmapped_routes_set = admin_known_unmapped_routes_set.union(
        api_known_unmapped_routes_set
    )

    def test_all_endpoints_owned(self, app):
        def rule_to_endpoint(rule):
            endpoint = str(rule)
            # the service mapper uses (.+?) where the flask routes use named params: correct for this
            endpoint = re.sub(r"\<.*?\>", "(.+?)", endpoint)
            return endpoint

        flask_route_set = {rule_to_endpoint(rule) for rule in app.url_map.iter_rules()}
        service_mapper_route_set = {
            endpoint for endpoint in endpoint_service_ns_mapper.keys()
        }

        # find all routes in flask which do not have a service mapped
        unmapped_routes = flask_route_set.difference(service_mapper_route_set)
        unexpected_unmapped_routes = unmapped_routes.difference(
            self.known_unmapped_routes_set
        )
        assert unexpected_unmapped_routes == set(), (
            "Please add new routes to utils.service_owner_mapper.endpoint_service_ns_mapper! \n"
            "Please DO NOT add new routes to the unmapped set in this test class! \n"
            f"New routes: {unexpected_unmapped_routes}"
        )

    def test_maintain_known_unmapped_routes(self):
        service_mapper_route_set = {
            endpoint for endpoint in endpoint_service_ns_mapper.keys()
        }
        routes_mapped_set = service_mapper_route_set.intersection(
            self.known_unmapped_routes_set
        )
        assert routes_mapped_set == set(), (
            "Please remove new mappings from the pytests.utils,test_service_owner_mapping.known_unmapped whitelist! "
            f"New mappings: {routes_mapped_set}"
        )

    def test_all_makers_owned(self):
        makers = set(FixtureSpecs.__members__.keys())
        mapped_makers = set(data_admin_maker_ns_mapper.keys())
        unmapped_makers = makers.difference(mapped_makers)
        assert unmapped_makers == set(), (
            "Please add new data-admin makers to utils.service_owner_mapper.data_admin_maker_ns_mapper! \n"
            f"New makers: {unmapped_makers}"
        )
