from enum import Enum

ASSET_UPLOAD_COMPLETE_METRIC = "asset.complete.count"
ASSET_UPLOAD_CANCELLED_METRIC = "asset.cancelled.count"
ASSET_CREATION_COMPLETE_METRIC = "asset.creation.complete.count"
ASSET_CREATION_ERROR_METRIC = "asset.creation.error.count"
ASSET_GET_ERROR_METRIC = "asset.get.error.count"
ZENDESK_UPDATE_COUNT_METRIC = "api.zendesk_update.count"
ZENDESK_WEBHOOK_SUCCESS_COUNT_METRIC = "api.zendesk_webhook.success.count"
ZENDESK_WEBHOOK_FAILURE_COUNT_METRIC = "api.zendesk_webhook.failure.count"
ZENDESK_API_SUCCESS_COUNT_METRICS = "api.zendesk.success.count"
ZENDESK_API_ERROR_COUNT_METRICS = "api.zendesk.error.count"
MESSAGE_CREATION_SUCCESS_COUNT_METRICS = "message.creation.success.count"
MESSAGE_CREATION_ERROR_COUNT_METRICS = "message.creation.error.count"

SEND_TO_ZENDESK_ERROR_COUNT_METRICS = "send_to_zendesk.error.count"
ZENDESK_RECONCILIATION_ERROR_COUNT_METRICS = "zendesk_reconciliation.error.count"

TWILIO_SMS_DELIVERY_ERROR = "twilio.webhook.error"
TWILIO_SMS_DELIVERY_SUCCESS_COUNT_METRICS = "twilio.webhook.success.count"
SMS_MISSING_PROFILE = "sms.error.missing_profile"
SMS_MISSING_PROFILE_NUMBER = "sms.error.missing_profile_number"
MAVEN_SMS_DELIVERY_ERROR = "sms.maven.error"

ZENDESK_MESSAGE_PROCESSING = "zendesk.message_processing"
ZENDESK_MESSAGE_PROCESSING_MESSAGE_TYPE = f"{ZENDESK_MESSAGE_PROCESSING}.message_type"
ZENDESK_MESSAGE_PROCESSING_OUTCOME = f"{ZENDESK_MESSAGE_PROCESSING}.outcome"
ZENDESK_MESSAGE_PROCESSING_LOCK_TIMEOUT = f"{ZENDESK_MESSAGE_PROCESSING}.lock_timeout"
ZENDESK_MESSAGE_PROCESSING_UNKNOWN_AUTHOR = (
    f"{ZENDESK_MESSAGE_PROCESSING}.unknown_author"
)
ZENDESK_MESSAGE_PROCESSING_LOOKBACK_CONFIG = (
    f"{ZENDESK_MESSAGE_PROCESSING}.lookback_config"
)
ZENDESK_ORG_UPDATE_CREATE_TIMEOUT = "zendesk.org_update_create.lock_timeout"
ZENDESK_USER_UPDATE_CREATE_TIMEOUT = "zendesk.user_update_create.lock_timeout"
ZENDESK_TICKET_PROCESSING_ERROR = "zendesk.ticket_processing.error"
ZENDESK_TICKET_MISSING_ERROR = "zendesk.ticket_processing.error"
ZENDESK_WEBHOOK_RECEIVED = "zendesk.webhook.received"

VIDEO_PLATFORM_SELECTION = "video.platform.selection"
VIDEO_PROBLEM_REPORTED = "video.problem.reported"


class UpdateZendeskFailureReason(Enum):
    NONE = 1
    ERROR_IN_GETTING_TICKET_IN_ZENDESK = 4  # Error in calling Zendesk API
    ERROR_IN_UPDATING_TICKET_COMMENT_IN_ZENDESK = 5  # Error in calling Zendesk API
    ERROR_IN_CREATING_TICKET_IN_ZENDESK = 6  # Error in calling Zendesk API
    ERROR_IN_UPDATING_DATA_FROM_ZENDESK = 7  # Error in connecting DB
    ERROR_IN_UPDATE_OR_CREATE_USER_IN_ZENDESK = 8  # Error in calling Zendesk API
    ERROR_IN_DATA_VALIDATING_IN_ZENDESK = 9  # Error in calling Zendesk API


class MessageCreationFailureReason(Enum):
    NONE = 1
    NO_PARTICIPANT_FOUND = 2
    USER_NOT_A_PARTICIPANT = 3
    INACTIVE_PRACTITIONER = 4
    MESSAGE_TOO_LONG = 5
    NO_ASSET_MATCHED = 6
    ASSET_BELONGING_TO_ANOTHER_USER = 7
    ASSET_NOT_COMPLETE = 8
    ATTACH_ASSET_TO_MULTIPLE_MESSAGES = 9
    NON_IMAGE_ASSET = 10
    MESSAGE_CREDITS_ALLOCATION_EXCEPTION = 11
    GENERAL_ALLOCATION_EXCEPTION = 12
    PRACTITIONER_HAS_MESSAGING_DISABLED = 13
    MESSAGE_CREDITS_ALLOCATION_EXCEPTION_ENTERPRISE = 14
    MEMBER_CANNOT_MESSAGE_PRACTITIONER = 15


class CronJobName(Enum):
    SMS_NOTIFY_UPCOMING_APPOINTMENTS_MEMBER_CRON_JOB = 1
    SMS_NOTIFY_UPCOMING_APPOINTMENTS_PRACTITIONER_CRON_JOB = 2
    CIGNA_ACCUMULATION_FILE_GENERATION = 3
    ESI_ACCUMULATION_FILE_GENERATION = 4
    UHC_ACCUMULATION_FILE_GENERATION = 5
    CIGNA_ACCUMULATION_DATA_SOURCING = 6
    ESI_ACCUMULATION_DATA_SOURCING = 7
    UHC_ACCUMULATION_DATA_SOURCING = 8
    TRANSFER_PAYER_ACCUMULATION_FILE_TO_CIGNA_DATA_SENDER = 9
    TRANSFER_PAYER_ACCUMULATION_FILE_TO_ESI_DATA_SENDER = 10
    TRANSFER_PAYER_ACCUMULATION_FILE_TO_UHC_DATA_SENDER = 11
    UPDATE_ORGANIZATION_APPROVED_MODULES = 12
    AETNA_ACCUMULATION_FILE_GENERATION = 13
    BACKFILL_GESTATIONAL_DIABETES = 14
    BACKFILL_CHRONIC_DIABETES = 15
    UPDATE_STAFF_PRACTITIONERS_PERCENT_BOOKED = 16
    FIND_TREATMENT_PROCEDURES_WITHOUT_COST_BREAKDOWN_IDS = 17
    ADD_SURVEY_IDS_TO_WEBHOOK = 18
    SEND_APPOINTMENT_COMPLETION_EVENT = 19
    DATA_CHECKER_HALF_HOURLY = 20
    CREATE_ZD_TICKET_FOR_UNRESPONDED_PROMOTED_MESSAGE = 21
    MEMBER_RISK_FLAGS_EVEN = 22
    MEMBER_RISK_FLAGS_ODD = 23
    SEND_CX_INTRO_MESSAGE_FOR_ENTERPRISE_USERS = 24
    FOLLOW_UP_WITH_USERS_WHO_PARTICIPATED_IN_ZOOM_WEBINAR = 25
    FOLLOW_UP_WITH_USERS_WHO_MISSED_ZOOM_WEBINAR = 26
    FIND_STALE_REQUEST_AVAILABILITY_MESSAGES_JOB = 27
    MEMBER_RISK_FLAGS = 28
