dag_id: create_zd_ticket_for_unresponded_promoted_messages_dag
schedule: "0 * * * *"
task_id: create_zd_ticket_for_unresponded_promoted_messages_job
commands:
  - "python3"
  - "-c"
  - "from airflow.scripts.care_discovery.create_zd_ticket_for_unresponded_promoted_messages import create_zd_ticket_for_unresponded_promoted_messages_job; create_zd_ticket_for_unresponded_promoted_messages_job()"
team_namespace: care_discovery
service_namespace: incentive
catchup: "False"
start_year: 2024
start_month: 10
start_day: 1
