dag_id: process_invoice_bills_dag
schedule: "0 17,20 * * *"
task_id: process_invoice_bills_job
commands:
  - "python3"
  - "-c"
  - "from airflow.scripts.benefits_experience.process_invoice_bills import process_invoice_bills_job; process_invoice_bills_job()"
team_namespace: benefits_experience
service_namespace: invoice
catchup: "False"
start_year: 2024
start_month: 10
start_day: 1