dag_id: send_cx_intro_message_for_enterprise_users_dag
schedule: "2 * * * *"
task_id: send_cx_intro_message_for_enterprise_users_job
commands:
  - "python3"
  - "-c"
  - "from airflow.scripts.care_discovery.send_cx_intro_message_for_enterprise_users import send_cx_intro_message_for_enterprise_users_job; send_cx_intro_message_for_enterprise_users_job()"
team_namespace: care_discovery
service_namespace: care_team
catchup: "False"
start_year: 2024
start_month: 10
start_day: 11