dag_id: sms_notify_upcoming_appointments_practitioner_dag
schedule: "*/5 * * * *"
task_id: sms_notify_upcoming_appointments_practitioner_job
commands:
  - "python3"
  - "-c"
  - "from airflow.scripts.virtual_care.sms_notify_upcoming_appointments_practitioner import sms_notify_upcoming_appointments_practitioner_job; sms_notify_upcoming_appointments_practitioner_job()"
team_namespace: virtual_care
service_namespace: appointment_notifications
catchup: "False"
start_year: 2024
start_month: 3
start_day: 31