# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from maven_schemas.eligibility import eligibility_test_utility_pb2 as maven__schemas_dot_eligibility_dot_eligibility__test__utility__pb2


class EligibilityTestUtilityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEligibilityMemberTestRecordsForOrganization = channel.unary_unary(
                '/maven.eligibility.eligibility_test_utility.EligibilityTestUtilityService/CreateEligibilityMemberTestRecordsForOrganization',
                request_serializer=maven__schemas_dot_eligibility_dot_eligibility__test__utility__pb2.CreateEligibilityMemberTestRecordsForOrganizationRequest.SerializeToString,
                response_deserializer=maven__schemas_dot_eligibility_dot_eligibility__test__utility__pb2.CreateEligibilityMemberTestRecordsForOrganizationResponse.FromString,
                )


class EligibilityTestUtilityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateEligibilityMemberTestRecordsForOrganization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EligibilityTestUtilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEligibilityMemberTestRecordsForOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEligibilityMemberTestRecordsForOrganization,
                    request_deserializer=maven__schemas_dot_eligibility_dot_eligibility__test__utility__pb2.CreateEligibilityMemberTestRecordsForOrganizationRequest.FromString,
                    response_serializer=maven__schemas_dot_eligibility_dot_eligibility__test__utility__pb2.CreateEligibilityMemberTestRecordsForOrganizationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'maven.eligibility.eligibility_test_utility.EligibilityTestUtilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EligibilityTestUtilityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateEligibilityMemberTestRecordsForOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/maven.eligibility.eligibility_test_utility.EligibilityTestUtilityService/CreateEligibilityMemberTestRecordsForOrganization',
            maven__schemas_dot_eligibility_dot_eligibility__test__utility__pb2.CreateEligibilityMemberTestRecordsForOrganizationRequest.SerializeToString,
            maven__schemas_dot_eligibility_dot_eligibility__test__utility__pb2.CreateEligibilityMemberTestRecordsForOrganizationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
