# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: maven-schemas/eligibility/pre_eligibility.proto
"""Generated protocol buffer code."""
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='maven-schemas/eligibility/pre_eligibility.proto',
    package='maven.pre_eligibility.pre_eligibility',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n/maven-schemas/eligibility/pre_eligibility.proto\x12%maven.pre_eligibility.pre_eligibility\x1a\x1fgoogle/protobuf/timestamp.proto\"y\n\x15PreEligibilityRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x11\n\tmember_id\x18\x02 \x01(\x03\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x15\n\rdate_of_birth\x18\x05 \x01(\t\"\xc8\x01\n\x16PreEligibilityResponse\x12\x44\n\nmatch_type\x18\x01 \x01(\x0e\x32\x30.maven.pre_eligibility.pre_eligibility.MatchType\x12h\n\x1dpre_eligibility_organizations\x18\x02 \x03(\x0b\x32\x41.maven.pre_eligibility.pre_eligibility.PreEligibilityOrganization\"o\n\x1aPreEligibilityOrganization\x12\x17\n\x0forganization_id\x18\x01 \x01(\x03\x12\x38\n\x14\x65ligibility_end_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*\x93\x01\n\tMatchType\x12\r\n\tPOTENTIAL\x10\x00\x12\"\n\x1ePOTENTIAL_CURRENT_ORGANIZATION\x10\x01\x12 \n\x1cPOTENTIAL_OTHER_ORGANIZATION\x10\x02\x12\x18\n\x14\x45XISTING_ELIGIBILITY\x10\x03\x12\x17\n\x13UNKNOWN_ELIGIBILITY\x10\x04\x32\xae\x01\n\x15PreEligibilityService\x12\x94\x01\n\x13\x43heckPreEligibility\x12<.maven.pre_eligibility.pre_eligibility.PreEligibilityRequest\x1a=.maven.pre_eligibility.pre_eligibility.PreEligibilityResponse\"\x00\x62\x06proto3',
    dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR])

_MATCHTYPE = _descriptor.EnumDescriptor(
    name='MatchType',
    full_name='maven.pre_eligibility.pre_eligibility.MatchType',
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name='POTENTIAL', index=0, number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
        _descriptor.EnumValueDescriptor(
            name='POTENTIAL_CURRENT_ORGANIZATION', index=1, number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
        _descriptor.EnumValueDescriptor(
            name='POTENTIAL_OTHER_ORGANIZATION', index=2, number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
        _descriptor.EnumValueDescriptor(
            name='EXISTING_ELIGIBILITY', index=3, number=3,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
        _descriptor.EnumValueDescriptor(
            name='UNKNOWN_ELIGIBILITY', index=4, number=4,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=563,
    serialized_end=710,
)
_sym_db.RegisterEnumDescriptor(_MATCHTYPE)

MatchType = enum_type_wrapper.EnumTypeWrapper(_MATCHTYPE)
POTENTIAL = 0
POTENTIAL_CURRENT_ORGANIZATION = 1
POTENTIAL_OTHER_ORGANIZATION = 2
EXISTING_ELIGIBILITY = 3
UNKNOWN_ELIGIBILITY = 4


_PREELIGIBILITYREQUEST = _descriptor.Descriptor(
    name='PreEligibilityRequest',
    full_name='maven.pre_eligibility.pre_eligibility.PreEligibilityRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='user_id', full_name='maven.pre_eligibility.pre_eligibility.PreEligibilityRequest.user_id', index=0,
            number=1, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='member_id', full_name='maven.pre_eligibility.pre_eligibility.PreEligibilityRequest.member_id', index=1,
            number=2, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='first_name', full_name='maven.pre_eligibility.pre_eligibility.PreEligibilityRequest.first_name', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='last_name', full_name='maven.pre_eligibility.pre_eligibility.PreEligibilityRequest.last_name', index=3,
            number=4, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='date_of_birth', full_name='maven.pre_eligibility.pre_eligibility.PreEligibilityRequest.date_of_birth', index=4,
            number=5, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=123,
    serialized_end=244,
)


_PREELIGIBILITYRESPONSE = _descriptor.Descriptor(
    name='PreEligibilityResponse',
    full_name='maven.pre_eligibility.pre_eligibility.PreEligibilityResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='match_type', full_name='maven.pre_eligibility.pre_eligibility.PreEligibilityResponse.match_type', index=0,
            number=1, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='pre_eligibility_organizations', full_name='maven.pre_eligibility.pre_eligibility.PreEligibilityResponse.pre_eligibility_organizations', index=1,
            number=2, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=247,
    serialized_end=447,
)


_PREELIGIBILITYORGANIZATION = _descriptor.Descriptor(
    name='PreEligibilityOrganization',
    full_name='maven.pre_eligibility.pre_eligibility.PreEligibilityOrganization',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='organization_id', full_name='maven.pre_eligibility.pre_eligibility.PreEligibilityOrganization.organization_id', index=0,
            number=1, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='eligibility_end_date', full_name='maven.pre_eligibility.pre_eligibility.PreEligibilityOrganization.eligibility_end_date', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=449,
    serialized_end=560,
)

_PREELIGIBILITYRESPONSE.fields_by_name['match_type'].enum_type = _MATCHTYPE
_PREELIGIBILITYRESPONSE.fields_by_name['pre_eligibility_organizations'].message_type = _PREELIGIBILITYORGANIZATION
_PREELIGIBILITYORGANIZATION.fields_by_name['eligibility_end_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['PreEligibilityRequest'] = _PREELIGIBILITYREQUEST
DESCRIPTOR.message_types_by_name['PreEligibilityResponse'] = _PREELIGIBILITYRESPONSE
DESCRIPTOR.message_types_by_name['PreEligibilityOrganization'] = _PREELIGIBILITYORGANIZATION
DESCRIPTOR.enum_types_by_name['MatchType'] = _MATCHTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PreEligibilityRequest = _reflection.GeneratedProtocolMessageType('PreEligibilityRequest', (_message.Message,), {
    'DESCRIPTOR': _PREELIGIBILITYREQUEST,
    '__module__': 'maven_schemas.eligibility.pre_eligibility_pb2'
    # @@protoc_insertion_point(class_scope:maven.pre_eligibility.pre_eligibility.PreEligibilityRequest)
})
_sym_db.RegisterMessage(PreEligibilityRequest)

PreEligibilityResponse = _reflection.GeneratedProtocolMessageType('PreEligibilityResponse', (_message.Message,), {
    'DESCRIPTOR': _PREELIGIBILITYRESPONSE,
    '__module__': 'maven_schemas.eligibility.pre_eligibility_pb2'
    # @@protoc_insertion_point(class_scope:maven.pre_eligibility.pre_eligibility.PreEligibilityResponse)
})
_sym_db.RegisterMessage(PreEligibilityResponse)

PreEligibilityOrganization = _reflection.GeneratedProtocolMessageType('PreEligibilityOrganization', (_message.Message,), {
    'DESCRIPTOR': _PREELIGIBILITYORGANIZATION,
    '__module__': 'maven_schemas.eligibility.pre_eligibility_pb2'
    # @@protoc_insertion_point(class_scope:maven.pre_eligibility.pre_eligibility.PreEligibilityOrganization)
})
_sym_db.RegisterMessage(PreEligibilityOrganization)


_PREELIGIBILITYSERVICE = _descriptor.ServiceDescriptor(
    name='PreEligibilityService',
    full_name='maven.pre_eligibility.pre_eligibility.PreEligibilityService',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=713,
    serialized_end=887,
    methods=[
        _descriptor.MethodDescriptor(
            name='CheckPreEligibility',
            full_name='maven.pre_eligibility.pre_eligibility.PreEligibilityService.CheckPreEligibility',
            index=0,
            containing_service=None,
            input_type=_PREELIGIBILITYREQUEST,
            output_type=_PREELIGIBILITYRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ]
)
_sym_db.RegisterServiceDescriptor(_PREELIGIBILITYSERVICE)

DESCRIPTOR.services_by_name['PreEligibilityService'] = _PREELIGIBILITYSERVICE

# @@protoc_insertion_point(module_scope)
